#!/usr/bin/env python3
"""/tc:automation-plan helper - Phase 6 Step 6.3.

Scans ``<workspace>/bdd/features/*.feature`` and scores each scenario against a
universal seven-factor automation-suitability rubric, then writes
``<workspace>/automation-plan/<area>.md`` ranking every scenario
``automate`` / ``consider`` / ``manual`` with its per-factor scores and a
recommended order. This is the strategic gate before any TypeScript is
generated by ``/tc:automate``.

The seven factors are mechanical, universal signals (D19) read straight from
the scenario's tags and steps:

- ``traceable``        - has a ``@req:``/``@cs:`` linkage tag.
- ``regression-value`` - carries a ``@smoke``/``@regression`` class tag.
- ``risk-flagged``     - carries a ``@risk:`` tag.
- ``deterministic``    - is NOT anomaly-derived (``@exploratory``/``@anomaly:``).
- ``right-sized``      - step count is within a healthy band.
- ``data-ready``       - not a ``Scenario Outline`` missing its ``Examples:``.
- ``persona-scoped``   - carries a ``@persona:`` tag.

Each present signal contributes its weight; the total is thresholded into a
rank. Two hard overrides bypass the score: ``@automated-candidate`` always ranks
``automate`` and ``@manual`` always ranks ``manual``. Weights are tunable via
``tc-automate.suitability.weights`` in ``<workspace>/config.yaml``.

Pure generated reports - overwrite mode; byte-deterministic re-run (scenarios
sort by name, features by filename). The README placeholder under
``automation-plan/`` is preserved.

Per D18 the helper ships inside the plugin. Mirrors ``review_bdd.py``: it reuses
that helper's ``parse_feature_file`` and follows the same workspace IO + config
+ scan + render + CLI shape.

Exit codes:
    0 - plan written (or no scenarios to plan).
    2 - precondition failure (uninitialized workspace).
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from review_bdd import ParsedScenario, parse_feature_file

WORKSPACE_DIRNAME = ".test-commander"

# Seven-factor rubric. Order fixes the plan's table columns.
FACTOR_NAMES = [
    "traceable",
    "regression-value",
    "risk-flagged",
    "deterministic",
    "right-sized",
    "data-ready",
    "persona-scoped",
]
DEFAULT_WEIGHTS: dict[str, int] = {
    "traceable": 3,
    "regression-value": 2,
    "risk-flagged": 2,
    "deterministic": 2,
    "right-sized": 1,
    "data-ready": 1,
    "persona-scoped": 1,
}
AUTOMATE_THRESHOLD = 8
CONSIDER_THRESHOLD = 5
RIGHT_SIZED_MIN = 3
RIGHT_SIZED_MAX = 12

CLASS_TAGS = {"@smoke", "@regression"}
RANK_ORDER = {"automate": 0, "consider": 1, "manual": 2}


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class AutomationPlanError(Exception):
    pass


class UninitializedWorkspaceError(AutomationPlanError):
    pass


# ---------------------------------------------------------------------------
# Data shapes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ScoredScenario:
    name: str
    rank: str
    total: int
    factor_scores: dict[str, int]


@dataclass
class PlanOutcome:
    area_count: int = 0
    scenario_count: int = 0
    plan_paths: list[Path] = field(default_factory=list)
    ranks_by_area: dict[str, dict[str, str]] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Workspace IO
# ---------------------------------------------------------------------------


def workspace_dir(project_root: Path) -> Path:
    ws = project_root / WORKSPACE_DIRNAME
    if not ws.is_dir():
        raise UninitializedWorkspaceError(
            f"not a Test Commander workspace: {project_root} "
            f"(no {WORKSPACE_DIRNAME}/). Run /tc:init first."
        )
    return ws


# ---------------------------------------------------------------------------
# Config extensions
# ---------------------------------------------------------------------------


def load_weights(workspace: Path) -> dict[str, int]:
    """Read ``tc-automate.suitability.weights`` and merge over the defaults.

    Tolerant: any read/parse error or an unknown factor name yields the default
    weight for that factor.
    """
    weights = dict(DEFAULT_WEIGHTS)
    config_path = workspace / "config.yaml"
    if not config_path.is_file():
        return weights
    try:
        import yaml

        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        configured = data["tc-automate"]["suitability"]["weights"]
    except Exception:
        return weights
    if not isinstance(configured, dict):
        return weights
    for name, value in configured.items():
        if name in weights:
            try:
                weights[name] = int(value)
            except (TypeError, ValueError):
                continue
    return weights


# ---------------------------------------------------------------------------
# Rubric
# ---------------------------------------------------------------------------


def factor_signals(sc: ParsedScenario) -> dict[str, bool]:
    tags = sc.tags
    anomaly = any(t == "@exploratory" or t.startswith("@anomaly:") for t in tags)
    return {
        "traceable": any(t.startswith("@req:") or t.startswith("@cs:") for t in tags),
        "regression-value": any(t in CLASS_TAGS for t in tags),
        "risk-flagged": any(t.startswith("@risk:") for t in tags),
        "deterministic": not anomaly,
        "right-sized": RIGHT_SIZED_MIN <= len(sc.steps) <= RIGHT_SIZED_MAX,
        "data-ready": not (sc.is_outline and not sc.has_examples),
        "persona-scoped": any(t.startswith("@persona:") for t in tags),
    }


def score_scenario(sc: ParsedScenario, weights: dict[str, int]) -> ScoredScenario:
    signals = factor_signals(sc)
    factor_scores = {
        name: (weights[name] if signals[name] else 0) for name in FACTOR_NAMES
    }
    total = sum(factor_scores.values())

    if "@automated-candidate" in sc.tags:
        rank = "automate"
    elif "@manual" in sc.tags:
        rank = "manual"
    elif total >= AUTOMATE_THRESHOLD:
        rank = "automate"
    elif total >= CONSIDER_THRESHOLD:
        rank = "consider"
    else:
        rank = "manual"
    return ScoredScenario(sc.name, rank, total, factor_scores)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _recommended_order(scored: list[ScoredScenario]) -> list[ScoredScenario]:
    """automate first, then consider, then manual; within a rank by score
    descending, then name ascending (deterministic)."""
    return sorted(scored, key=lambda s: (RANK_ORDER[s.rank], -s.total, s.name))


def render_plan(area: str, scored: list[ScoredScenario]) -> str:
    by_name = sorted(scored, key=lambda s: s.name)
    counts = {rank: sum(1 for s in scored if s.rank == rank) for rank in RANK_ORDER}

    lines: list[str] = []
    lines.append(f"# Automation plan - {area}")
    lines.append("")
    lines.append(f"_Generated by /tc:automation-plan from bdd/features/{area}.feature._")
    lines.append("")
    lines.append(f"- Scenarios: {len(scored)}")
    lines.append(
        f"- automate: {counts['automate']}, "
        f"consider: {counts['consider']}, manual: {counts['manual']}"
    )
    lines.append("")
    lines.append("## Ranking")
    lines.append("")
    header = ["scenario", "rank", "score", *FACTOR_NAMES]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("| " + " | ".join("---" for _ in header) + " |")
    for s in by_name:
        cells = [s.name, s.rank, str(s.total)]
        cells.extend(str(s.factor_scores[f]) for f in FACTOR_NAMES)
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("## Recommended order")
    lines.append("")
    automatable = [s for s in _recommended_order(scored) if s.rank != "manual"]
    if not automatable:
        lines.append("_No automate/consider scenarios; everything is manual._")
    else:
        for i, s in enumerate(automatable, start=1):
            lines.append(f"{i}. {s.name} ({s.rank}, score {s.total})")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def build_plan(project_root: Path) -> PlanOutcome:
    workspace = workspace_dir(project_root)
    weights = load_weights(workspace)
    features_dir = workspace / "bdd" / "features"
    feats = sorted(features_dir.glob("*.feature")) if features_dir.is_dir() else []

    plan_dir = workspace / "automation-plan"
    outcome = PlanOutcome()
    for path in feats:
        area = path.stem
        scored = [score_scenario(sc, weights) for sc in parse_feature_file(path)]
        if not scored:
            continue
        plan_dir.mkdir(parents=True, exist_ok=True)
        plan_file = plan_dir / f"{area}.md"
        plan_file.write_text(render_plan(area, scored), encoding="utf-8")
        outcome.area_count += 1
        outcome.scenario_count += len(scored)
        outcome.plan_paths.append(plan_file)
        outcome.ranks_by_area[area] = {s.name: s.rank for s in scored}
    return outcome


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Score BDD scenarios for automation suitability against the "
            "seven-factor rubric and write automation-plan/<area>.md ranking "
            "each scenario automate/consider/manual."
        ),
    )
    parser.add_argument(
        "project_root",
        nargs="?",
        default=".",
        help="Project root (default: current directory).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    project_root = Path(args.project_root).resolve()

    try:
        outcome = build_plan(project_root)
    except UninitializedWorkspaceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if outcome.area_count == 0:
        print("no scenarios to plan (run /tc:generate-bdd first)")
        return 0

    print(
        f"planned: {outcome.area_count} area(s) "
        f"({outcome.scenario_count} scenario(s))"
    )
    for path in outcome.plan_paths:
        print(f"  - {path.relative_to(project_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
