#!/usr/bin/env python3
"""/tc:build-framework helper - Phase 6 Step 6.2.

Scaffolds the project-root Playwright/TypeScript automation framework lazily
(Decision D8): the ``tests/{e2e,pages,components,fixtures,utils}/`` tree plus
``tests/playwright.config.ts`` and ``tests/package.json``. Each managed path is
created only when absent, so a re-run is a byte-stable no-op and a partial tree
converges without clobbering user edits.

``ensure_framework(project_root)`` is the lazy-init entry point the Phase 6.4
generator (``/tc:automate``) calls before rendering any TypeScript: if the
framework is already present every path is skipped; otherwise it is built.

The framework lands at the project root ``tests/`` tree, *outside* the
``.test-commander/`` workspace (the cross-phase write boundary). The helper
still refuses to run against an uninitialized workspace, like every other
``/tc:`` command.

This helper only writes TypeScript and JSON text - it never invokes ``tsc`` or
Playwright and never reaches a browser. Execution is Phase 7's ``/tc:run``.

Per D18 the helper ships inside the plugin. The generated config and
``package.json`` are universal (D19): a consuming project sets its own
``baseURL`` via the ``PLAYWRIGHT_BASE_URL`` environment variable.

Exit codes:
    0 - framework present (built or already there).
    2 - precondition failure (uninitialized workspace).
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

WORKSPACE_DIRNAME = ".test-commander"
FRAMEWORK_DIRNAME = "tests"
SENTINEL = "playwright.config.ts"
SUBDIRS = ("e2e", "pages", "components", "fixtures", "utils")


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class BuildFrameworkError(Exception):
    pass


class UninitializedWorkspaceError(BuildFrameworkError):
    pass


# ---------------------------------------------------------------------------
# Outcome
# ---------------------------------------------------------------------------


@dataclass
class BuildOutcome:
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Workspace IO
# ---------------------------------------------------------------------------


def workspace_dir(project_root: Path) -> Path:
    ws = project_root / WORKSPACE_DIRNAME
    if not ws.is_dir():
        raise UninitializedWorkspaceError(
            f"not a Test Commander workspace: {project_root} "
            f"(no {WORKSPACE_DIRNAME}/). Run /tc:init first."
        )
    return ws


# ---------------------------------------------------------------------------
# Bundled framework files (rendered inline, like the sibling generators)
# ---------------------------------------------------------------------------

PLAYWRIGHT_CONFIG_TS = """\
// Generated by /tc:build-framework. Test Commander's lazy Playwright framework.
// Universal config (D19): set the target via the PLAYWRIGHT_BASE_URL env var.
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [['list'], ['html', { open: 'never' }]],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
"""

PACKAGE_JSON = """\
{
  "name": "test-commander-automation",
  "version": "0.1.0",
  "private": true,
  "description": "Playwright automation framework generated by Test Commander.",
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "report": "playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.49.0",
    "typescript": "^5.7.0"
  }
}
"""

GITKEEP = ""


def framework_files() -> dict[str, str]:
    """Relative-to-``tests/`` path -> file content for the scaffold."""
    return {
        SENTINEL: PLAYWRIGHT_CONFIG_TS,
        "package.json": PACKAGE_JSON,
    }


# ---------------------------------------------------------------------------
# Scaffold
# ---------------------------------------------------------------------------


def _create_or_skip(path: Path, content: str, rel: str, outcome: BuildOutcome) -> None:
    if path.exists():
        outcome.skipped.append(rel)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    outcome.created.append(rel)


def scaffold(project_root: Path) -> BuildOutcome:
    """Build the framework, creating each managed path only when absent.

    Idempotent and byte-stable: a path that already exists is reported skipped
    and left untouched, so a re-run creates nothing.
    """
    workspace_dir(project_root)  # refuse uninitialized, like every /tc: command
    tests_dir = project_root / FRAMEWORK_DIRNAME

    outcome = BuildOutcome()
    for sub in SUBDIRS:
        keep = tests_dir / sub / ".gitkeep"
        _create_or_skip(keep, GITKEEP, f"{sub}/.gitkeep", outcome)
    for name, content in framework_files().items():
        _create_or_skip(tests_dir / name, content, name, outcome)
    return outcome


def ensure_framework(project_root: Path) -> BuildOutcome:
    """Lazy-init entry point for the Phase 6.4 generator.

    Builds the framework only if the ``tests/playwright.config.ts`` sentinel is
    absent; otherwise returns an all-skipped outcome without touching disk.
    """
    workspace_dir(project_root)
    sentinel = project_root / FRAMEWORK_DIRNAME / SENTINEL
    if sentinel.exists():
        skipped = [f"{sub}/.gitkeep" for sub in SUBDIRS] + list(framework_files())
        return BuildOutcome(skipped=skipped)
    return scaffold(project_root)


def run(project_root: Path) -> BuildOutcome:
    return scaffold(project_root)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Scaffold the project-root Playwright/TypeScript framework lazily. "
            "Creates tests/{e2e,pages,components,fixtures,utils}/, "
            "tests/playwright.config.ts, and tests/package.json only when absent."
        ),
    )
    parser.add_argument(
        "project_root",
        nargs="?",
        default=".",
        help="Project root (default: current directory).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    project_root = Path(args.project_root).resolve()

    try:
        outcome = run(project_root)
    except UninitializedWorkspaceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"framework: created {len(outcome.created)}, skipped {len(outcome.skipped)}")
    for rel in outcome.created:
        print(f"  + tests/{rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
