#!/usr/bin/env python3
"""/tc:learn-from-code helper - Phase 3 Step 3.4.

Walks the configured source root (default ``<workspace>/documents/uploaded/
code/``) and extracts Python modules, classes, functions, docstrings, and
decorators using the stdlib ``ast`` module. Non-Python source files
(``.ts/.tsx/.js/.jsx/.go/.java/.rb``) are detected by extension and counted
as ``language-unsupported-in-v1`` gaps - never silently ignored.

Writes:

- ``<workspace>/product-knowledge/code-derived-model.md`` - overwritten
  byte-deterministically.
- The ``## From code`` section in ``entities.md`` (classes contribute as
  domain entities). ``business-rules.md`` receives a ``## From code``
  section only if module-level constants carry an explicit rule docstring;
  the section is omitted otherwise. ``user-journeys.md`` and
  ``assumptions.md`` are NOT touched.
- Gap-signal questions appended to
  ``<workspace>/requirements/open-questions.md`` with the Phase-2 dedup
  contract (``source-id, question-text``).
- ``<workspace>/product-knowledge/system-model.md`` regenerated via the
  shared ``synthesize_system_model.py`` helper.

Per D18 the helper ships inside the plugin. Per D19 the language detector
and the keyword sets are universal cores; projects extend via
``tc-knowledge.code:`` in ``<workspace>/config.yaml``.

Exit codes:
    0 - code-derived-model written.
    2 - uninitialized workspace.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

# Local-package imports.
import synthesize_system_model as synth_mod

WORKSPACE_DIRNAME = ".test-commander"
SOURCE_LABEL = "code"

DEFAULT_SOURCE_ROOT = "documents/uploaded/code"
DEFAULT_ENABLED_LANGUAGES = ("python",)
DEFAULT_IGNORED_PATHS = ("__pycache__", ".git", ".venv", "node_modules")
UNSUPPORTED_LANG_EXTENSIONS = (".ts", ".tsx", ".js", ".jsx", ".go", ".java", ".rb")

# Marker the helper for /tc:learn-from-specs uses when it produces its model.
SPEC_MODEL_GENERATED_MARKER = "Auto-generated by `/tc:learn-from-specs`"


class CodeError(Exception):
    pass


class UninitializedWorkspaceError(CodeError):
    pass


# ---------------------------------------------------------------------------
# Data shapes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Module:
    rel_path: str
    line_count: int
    docstring: str | None


@dataclass(frozen=True)
class Class:
    name: str
    docstring: str | None
    bases: tuple[str, ...]
    attributes: tuple[str, ...]
    source_file: str
    line: int


@dataclass(frozen=True)
class Function:
    name: str
    docstring: str | None
    decorators: tuple[str, ...]
    source_file: str
    line: int
    is_async: bool


@dataclass(frozen=True)
class GapSignal:
    kind: str
    description: str
    source_file: str | None
    line: int | None


@dataclass
class Extensions:
    source_root: str = DEFAULT_SOURCE_ROOT
    enabled_languages: tuple[str, ...] = DEFAULT_ENABLED_LANGUAGES
    ignored_paths: tuple[str, ...] = DEFAULT_IGNORED_PATHS


@dataclass
class CodeFindings:
    modules: list[Module] = field(default_factory=list)
    classes: list[Class] = field(default_factory=list)
    functions: list[Function] = field(default_factory=list)
    unsupported_files: list[tuple[str, str]] = field(default_factory=list)  # (rel_path, ext)
    gaps: list[GapSignal] = field(default_factory=list)


# ---------------------------------------------------------------------------
# IO + workspace resolution (mirrors 3.2/3.3)
# ---------------------------------------------------------------------------


def workspace_dir(project_root: Path) -> Path:
    ws = project_root / WORKSPACE_DIRNAME
    if not ws.is_dir():
        raise UninitializedWorkspaceError(
            f"not a Test Commander workspace: {project_root} (no {WORKSPACE_DIRNAME}/)"
        )
    return ws


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


def _parse_inline_list(value: str) -> list[str]:
    inner = value.strip()
    if inner.startswith("[") and inner.endswith("]"):
        inner = inner[1:-1]
    items: list[str] = []
    for raw in inner.split(","):
        item = raw.strip().strip("'\"")
        if item:
            items.append(item)
    return items


def load_extensions(workspace: Path) -> Extensions:
    """Read ``tc-knowledge.code:`` extensions from ``<workspace>/config.yaml``.

    Tolerant indentation-based parser; falls back to documented defaults when
    keys are absent. Recognized keys: ``source-root``, ``enabled-languages``,
    ``ignored-paths``. (``endpoint-decorator-patterns`` is documented for
    future use; v1 does not consume it.)
    """
    ext = Extensions()
    config_path = workspace / "config.yaml"
    if not config_path.is_file():
        return ext
    try:
        text = config_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ext

    in_root = False
    section: str | None = None
    pending_key: str | None = None
    pending_items: list[str] = []

    def commit() -> None:
        nonlocal pending_key, pending_items
        if pending_key is not None and section == "code":
            _assign(ext, pending_key, pending_items)
        pending_key = None
        pending_items = []

    for raw in text.split("\n"):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))

        if indent == 0:
            commit()
            section = None
            in_root = stripped == "tc-knowledge:"
            continue
        if not in_root:
            continue

        if indent == 2:
            commit()
            section = stripped[:-1].strip() if stripped.endswith(":") else None
            continue

        if indent == 4 and section == "code":
            commit()
            if ":" not in stripped:
                continue
            key, _, value = stripped.partition(":")
            key = key.strip()
            value = value.strip()
            if value:
                if value.startswith("["):
                    items = _parse_inline_list(value)
                    _assign(ext, key, items)
                else:
                    _assign(ext, key, [value.strip("'\"")])
            else:
                pending_key = key
                pending_items = []
            continue

        if indent >= 6 and pending_key is not None and stripped.startswith("-"):
            item = stripped[1:].strip().strip("'\"")
            if item:
                pending_items.append(item)

    commit()
    return ext


def _assign(ext: Extensions, key: str, items: list[str]) -> None:
    if not items:
        return
    if key == "source-root":
        ext.source_root = items[0]
    elif key == "enabled-languages":
        ext.enabled_languages = tuple(items)
    elif key == "ignored-paths":
        ext.ignored_paths = tuple(items)


# ---------------------------------------------------------------------------
# Source discovery
# ---------------------------------------------------------------------------


def _is_ignored(path: Path, root: Path, ignored: Iterable[str]) -> bool:
    rel_parts = path.relative_to(root).parts
    return any(part in ignored for part in rel_parts) or any(
        token in str(path.relative_to(root)) for token in ignored
    )


def discover_python(root: Path, ignored: Iterable[str]) -> list[Path]:
    if not root.is_dir():
        return []
    found: list[Path] = []
    for path in sorted(root.rglob("*.py")):
        if not path.is_file():
            continue
        if _is_ignored(path, root, ignored):
            continue
        found.append(path)
    return found


def discover_unsupported(root: Path, ignored: Iterable[str]) -> list[Path]:
    if not root.is_dir():
        return []
    found: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in UNSUPPORTED_LANG_EXTENSIONS:
            continue
        if _is_ignored(path, root, ignored):
            continue
        found.append(path)
    return found


# ---------------------------------------------------------------------------
# AST extraction
# ---------------------------------------------------------------------------


def _format_decorator(node: ast.expr) -> str:
    """Render a decorator expression back to a source-like string."""
    if isinstance(node, ast.Name):
        return f"@{node.id}"
    if isinstance(node, ast.Attribute):
        parts: list[str] = [node.attr]
        current = node.value
        while isinstance(current, ast.Attribute):
            parts.append(current.attr)
            current = current.value
        if isinstance(current, ast.Name):
            parts.append(current.id)
        return "@" + ".".join(reversed(parts))
    if isinstance(node, ast.Call):
        return _format_decorator(node.func) + "(...)"
    return "@<expr>"


def _attributes_from_init(class_node: ast.ClassDef) -> tuple[str, ...]:
    attrs: list[str] = []
    for member in class_node.body:
        is_init_def = isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef))
        if is_init_def and member.name == "__init__":
            for stmt in member.body:
                if isinstance(stmt, ast.Assign):
                    for target in stmt.targets:
                        if (
                            isinstance(target, ast.Attribute)
                            and isinstance(target.value, ast.Name)
                            and target.value.id == "self"
                        ):
                            attrs.append(target.attr)
                elif (
                    isinstance(stmt, ast.AnnAssign)
                    and isinstance(stmt.target, ast.Attribute)
                    and isinstance(stmt.target.value, ast.Name)
                    and stmt.target.value.id == "self"
                ):
                    attrs.append(stmt.target.attr)
            break
    return tuple(attrs)


def extract_python(path: Path, rel_path: str) -> tuple[Module | None, list[Class], list[Function]]:
    text = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError:
        return None, [], []

    module = Module(
        rel_path=rel_path,
        line_count=text.count("\n") + 1,
        docstring=ast.get_docstring(tree),
    )

    classes: list[Class] = []
    functions: list[Function] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases: list[str] = []
            for base in node.bases:
                if isinstance(base, ast.Name):
                    bases.append(base.id)
                elif isinstance(base, ast.Attribute):
                    bases.append(_format_decorator(base).lstrip("@"))
            classes.append(
                Class(
                    name=node.name,
                    docstring=ast.get_docstring(node),
                    bases=tuple(bases),
                    attributes=_attributes_from_init(node),
                    source_file=rel_path,
                    line=node.lineno,
                )
            )
            # Also capture top-level methods as functions (with their class qualified name).
            for member in node.body:
                is_method = isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef))
                if is_method and not member.name.startswith("_"):
                    functions.append(
                        Function(
                            name=f"{node.name}.{member.name}",
                            docstring=ast.get_docstring(member),
                            decorators=tuple(_format_decorator(d) for d in member.decorator_list),
                            source_file=rel_path,
                            line=member.lineno,
                            is_async=isinstance(member, ast.AsyncFunctionDef),
                        )
                    )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(
                Function(
                    name=node.name,
                    docstring=ast.get_docstring(node),
                    decorators=tuple(_format_decorator(d) for d in node.decorator_list),
                    source_file=rel_path,
                    line=node.lineno,
                    is_async=isinstance(node, ast.AsyncFunctionDef),
                )
            )

    return module, classes, functions


# ---------------------------------------------------------------------------
# Spec cross-check
# ---------------------------------------------------------------------------


SPEC_ENDPOINT_ROW_RE = re.compile(
    r"^\|\s*([A-Z]+)\s+(\S[^|]*?)\s*\|\s*([^|]*?)\s*\|"
)


def parse_spec_endpoints(workspace: Path) -> list[tuple[str, str, str]]:
    """Return [(method, path, operation_id), ...] from spec-derived-model.md.

    Returns an empty list when the file is still the workspace-template stub
    or carries any helper-emitted empty-run sentinel.
    """
    spec_model = workspace / "product-knowledge" / "spec-derived-model.md"
    if not spec_model.is_file():
        return []
    text = spec_model.read_text(encoding="utf-8")
    if SPEC_MODEL_GENERATED_MARKER not in text:
        return []
    if "no spec found" in text.lower():
        return []

    endpoints: list[tuple[str, str, str]] = []
    in_endpoints_section = False
    for line in text.splitlines():
        if line.startswith("## Endpoints"):
            in_endpoints_section = True
            continue
        if line.startswith("## ") and in_endpoints_section:
            break
        if not in_endpoints_section:
            continue
        m = SPEC_ENDPOINT_ROW_RE.match(line)
        if not m:
            continue
        method, path, operation = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
        if method == "Endpoint" or method.startswith("-"):
            continue
        endpoints.append((method, path, operation))
    return endpoints


def detect_unimplemented_endpoints(
    workspace: Path, functions: list[Function]
) -> list[GapSignal]:
    """Cross-check spec endpoints against parsed function names.

    Match rule: an endpoint is considered implemented iff its
    ``operationId`` equals any plain function name (the qualified
    ``Class.method`` form is also matched against its trailing segment).
    """
    endpoints = parse_spec_endpoints(workspace)
    if not endpoints:
        return []
    function_names: set[str] = set()
    for fn in functions:
        function_names.add(fn.name)
        if "." in fn.name:
            function_names.add(fn.name.split(".", 1)[1])
    gaps: list[GapSignal] = []
    for method, path, operation in endpoints:
        if not operation:
            continue  # cannot match without an operationId.
        if operation in function_names:
            continue
        gaps.append(
            GapSignal(
                kind="unimplemented-endpoint",
                description=(
                    f"Spec endpoint {method} {path} (operationId "
                    f"'{operation}') has no matching function in the parsed "
                    "code"
                ),
                source_file=None,
                line=None,
            )
        )
    return gaps


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


def aggregate(workspace: Path, ext: Extensions) -> CodeFindings:
    source_root = (workspace / ext.source_root).resolve()
    findings = CodeFindings()

    if "python" not in (lang.lower() for lang in ext.enabled_languages):
        # v1 only parses Python; an empty enabled-languages list means no parse.
        return findings

    for path in discover_python(source_root, ext.ignored_paths):
        rel_path = str(path.relative_to(workspace))
        module, classes, functions = extract_python(path, rel_path)
        if module is not None:
            findings.modules.append(module)
        findings.classes.extend(classes)
        findings.functions.extend(functions)

    for path in discover_unsupported(source_root, ext.ignored_paths):
        rel_path = str(path.relative_to(workspace))
        ext_suffix = path.suffix.lower()
        findings.unsupported_files.append((rel_path, ext_suffix))
        findings.gaps.append(
            GapSignal(
                kind="language-unsupported-in-v1",
                description=(
                    f"File {rel_path} has extension {ext_suffix}; the helper "
                    "detects the language but does not parse it in v1"
                ),
                source_file=rel_path,
                line=1,
            )
        )

    # undocumented-function gap (public name without a docstring).
    for fn in findings.functions:
        if fn.name.startswith("_"):
            continue
        if "." in fn.name and fn.name.split(".", 1)[1].startswith("_"):
            continue
        if fn.docstring is not None and fn.docstring.strip():
            continue
        findings.gaps.append(
            GapSignal(
                kind="undocumented-function",
                description=(
                    f"Public function '{fn.name}' in {fn.source_file} has no "
                    "docstring"
                ),
                source_file=fn.source_file,
                line=fn.line,
            )
        )

    # unimplemented-endpoint gap (only when spec-derived-model.md is generated).
    findings.gaps.extend(detect_unimplemented_endpoints(workspace, findings.functions))

    return findings


# ---------------------------------------------------------------------------
# Per-source render (code-derived-model.md)
# ---------------------------------------------------------------------------


def _first_line(docstring: str | None) -> str:
    if not docstring:
        return ""
    return docstring.strip().splitlines()[0]


def render_code_model(findings: CodeFindings) -> str:
    lines: list[str] = []
    lines.append("# Code-Derived Model")
    lines.append("")
    lines.append(
        "Auto-generated by `/tc:learn-from-code`. Re-running overwrites this "
        "file byte-deterministically. Edits will not survive a re-run."
    )
    lines.append("")

    lines.append("## Source modules")
    lines.append("")
    if not findings.modules and not findings.unsupported_files:
        lines.append("_No code source found._")
        lines.append("")
        lines.append(
            "Configure the source root via `tc-knowledge.code.source-root` in "
            "`<workspace>/config.yaml`. Default: `documents/uploaded/code`. "
            "Recognized v1 language: Python."
        )
        lines.append("")
        return "\n".join(lines).rstrip("\n") + "\n"

    if findings.modules:
        lines.append("| Module | Lines |")
        lines.append("| --- | --- |")
        for module in sorted(findings.modules, key=lambda m: m.rel_path):
            lines.append(f"| {module.rel_path} | {module.line_count} |")
    else:
        lines.append("_No Python modules parsed._")
    lines.append("")

    # Classes
    lines.append("## Classes")
    lines.append("")
    if findings.classes:
        lines.append("| Class | Attributes | Source |")
        lines.append("| --- | --- | --- |")
        for cls in sorted(findings.classes, key=lambda c: (c.name, c.source_file, c.line)):
            attrs = ", ".join(cls.attributes) if cls.attributes else ""
            lines.append(f"| {cls.name} | {attrs} | {cls.source_file}:{cls.line} |")
        lines.append("")
        for cls in sorted(findings.classes, key=lambda c: (c.name, c.source_file)):
            summary = _first_line(cls.docstring)
            if summary:
                lines.append(f"- **{cls.name}** ({cls.source_file}:{cls.line}) - {summary}")
        if any(_first_line(c.docstring) for c in findings.classes):
            lines.append("")
    else:
        lines.append("_No classes extracted._")
        lines.append("")

    # Functions
    lines.append("## Functions")
    lines.append("")
    if findings.functions:
        lines.append("| Function | Decorators | Source |")
        lines.append("| --- | --- | --- |")
        for fn in sorted(findings.functions, key=lambda f: (f.name, f.source_file, f.line)):
            decorators = ", ".join(fn.decorators) if fn.decorators else ""
            kind = "async " if fn.is_async else ""
            lines.append(
                f"| {kind}{fn.name} | {decorators} | {fn.source_file}:{fn.line} |"
            )
        lines.append("")
        for fn in sorted(findings.functions, key=lambda f: (f.name, f.source_file)):
            summary = _first_line(fn.docstring)
            if summary:
                lines.append(f"- **{fn.name}** ({fn.source_file}:{fn.line}) - {summary}")
        if any(_first_line(f.docstring) for f in findings.functions):
            lines.append("")
    else:
        lines.append("_No functions extracted._")
        lines.append("")

    # Languages detected but not parsed
    lines.append("## Languages detected but not parsed in v1")
    lines.append("")
    if findings.unsupported_files:
        lines.append("| File | Extension |")
        lines.append("| --- | --- |")
        for rel_path, ext_suffix in sorted(findings.unsupported_files):
            lines.append(f"| {rel_path} | {ext_suffix} |")
    else:
        lines.append("_No non-Python source files detected._")
    lines.append("")

    # Gap signals
    lines.append("## Gap signals (routed to `requirements/open-questions.md`)")
    lines.append("")
    if findings.gaps:
        for gap in sorted(
            findings.gaps,
            key=lambda g: (g.kind, g.source_file or "", g.line or 0),
        ):
            citation = ""
            if gap.source_file and gap.line:
                citation = f" ({gap.source_file}:{gap.line})"
            lines.append(f"- **{gap.kind}**: {gap.description}{citation}")
    else:
        lines.append("_No gap signals detected._")
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Cross-cutting render
# ---------------------------------------------------------------------------


def render_code_entities_section(findings: CodeFindings) -> str:
    if not findings.classes:
        return "_No classes extracted from code._"
    lines: list[str] = []
    for cls in sorted(findings.classes, key=lambda c: (c.name, c.source_file, c.line)):
        summary = _first_line(cls.docstring)
        suffix = f" - {summary}" if summary else ""
        lines.append(f"- **{cls.name}** ({cls.source_file}:{cls.line}){suffix}")
    return "\n".join(lines)


# Rule-docstring constants: not exercised by v1's seeded fixture, but the
# render is in place so 3.4 can still write a (typically empty) "## From code"
# section when warranted. Returns an empty string to indicate "no contribution",
# which makes _render_cross_cutting skip the section entirely.
def render_code_rules_section(_findings: CodeFindings) -> str:
    return ""


# ---------------------------------------------------------------------------
# Cross-cutting file IO (mirrors 3.2/3.3)
# ---------------------------------------------------------------------------


CROSS_CUTTING_TITLES: dict[str, tuple[str, str]] = {
    "entities.md": (
        "Entities",
        "Cross-source entity index. Each `## From <source>` section is "
        "regenerated by its owning `/tc:learn-from-*` command; sections from "
        "other commands are preserved across re-runs.",
    ),
    "business-rules.md": (
        "Business Rules",
        "Cross-source business-rule index. Each `## From <source>` section is "
        "regenerated by its owning `/tc:learn-from-*` command; sections from "
        "other commands are preserved across re-runs.",
    ),
}

SOURCE_ORDER = ("documents", "specs", "code", "api", "tests")


def update_cross_cutting(workspace: Path, filename: str, section_body: str) -> None:
    target = workspace / "product-knowledge" / filename
    title, preamble = CROSS_CUTTING_TITLES[filename]
    sections = synth_mod.parse_source_sections(_read_text(target))
    sections[SOURCE_LABEL] = section_body.strip()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_render_cross_cutting(title, preamble, sections), encoding="utf-8")


def _render_cross_cutting(title: str, preamble: str, sections: dict[str, str]) -> str:
    lines: list[str] = [f"# {title}", "", preamble, ""]
    for source in SOURCE_ORDER:
        body = sections.get(source, "").strip()
        if not body:
            continue
        lines.append(f"## From {source}")
        lines.append("")
        lines.append(body)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _read_text(path: Path) -> str:
    if not path.is_file():
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""


# ---------------------------------------------------------------------------
# Open-questions append (mirrors 3.2/3.3)
# ---------------------------------------------------------------------------


OPEN_QUESTIONS_HEADER = "# Open questions"


def append_open_questions(workspace: Path, gaps: list[GapSignal]) -> None:
    target = workspace / "requirements" / "open-questions.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    existing = _read_text(target)
    if not existing.strip():
        existing = (
            f"{OPEN_QUESTIONS_HEADER}\n\n"
            "Append-only log of questions raised by tc-knowledge and other "
            "commands. Deduplicated by source-id + question text.\n"
        )

    existing_set: set[tuple[str, str]] = set()
    for line in existing.split("\n"):
        m = re.match(r"^- \[([^\]]+)\]\s+(.+)$", line)
        if m:
            existing_set.add((m.group(1).strip(), m.group(2).strip()))

    new_lines: list[str] = []
    for gap in gaps:
        source_id = "tc-knowledge/learn-from-code"
        question = f"[{gap.kind}] {gap.description.rstrip('.')}."
        key = (source_id, question)
        if key in existing_set:
            continue
        existing_set.add(key)
        new_lines.append(f"- [{source_id}] {question}")

    if not new_lines:
        if existing.endswith("\n"):
            target.write_text(existing, encoding="utf-8")
        else:
            target.write_text(existing + "\n", encoding="utf-8")
        return

    body = existing.rstrip("\n") + "\n\n" + "\n".join(new_lines) + "\n"
    target.write_text(body, encoding="utf-8")


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def run(project_root: Path) -> int:
    workspace = workspace_dir(project_root)
    ext = load_extensions(workspace)
    findings = aggregate(workspace, ext)

    # 1. code-derived-model.md
    code_model = workspace / "product-knowledge" / "code-derived-model.md"
    code_model.parent.mkdir(parents=True, exist_ok=True)
    code_model.write_text(render_code_model(findings), encoding="utf-8")

    # 2. cross-cutting section-overwrites (entities; business-rules only when
    # render produces a non-empty body).
    update_cross_cutting(workspace, "entities.md", render_code_entities_section(findings))
    update_cross_cutting(
        workspace, "business-rules.md", render_code_rules_section(findings)
    )

    # 3. open-questions
    append_open_questions(workspace, findings.gaps)

    # 4. synthesizer
    synth_mod.synthesize(project_root)

    return 0


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Extract knowledge from Python source under the configured root "
            "(default <workspace>/documents/uploaded/code/) and populate "
            "<workspace>/product-knowledge/."
        ),
    )
    parser.add_argument(
        "project_root",
        nargs="?",
        default=".",
        help="Project root (default: current directory).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    project_root = Path(args.project_root).resolve()

    try:
        return run(project_root)
    except UninitializedWorkspaceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
