#!/usr/bin/env python3
"""/tc:generate-test-data helper - Phase 6 Step 6.6.

Populates ``<workspace>/test-data/`` from the BDD scenarios so the per-area
fixture ``/tc:automate`` generates can reach its data through a file rather than
inlining it (Decision D6). For each ``bdd/features/<area>.feature`` it writes:

- ``test-data/seed/<area>.json`` - a JSON fixture (the file the generated
  fixture loads). Carries one record per ``@cs:`` candidate scenario.
- ``test-data/scenarios/<area>.md`` - a Markdown spec listing each scenario's
  declarative data requirement (the Q11 "Markdown specs" surface).

Per Open Question Q11, declarative formats (JSON fixtures + Markdown specs)
cover the universal case; Python factories under ``test-data/factories/`` are
authored by hand only where a generator is too complex to express
declaratively, and are never overwritten here.

Overwrite mode for *generated* files (those carrying the generated marker);
**skip-not-overwrite** for user-authored files (no marker), so hand-tuned data
survives regeneration. Deterministic: records sort by ``@cs:`` id; byte-stable
re-run.

The shipped data shape is universal (D19): generic records keyed by candidate
id, with no product-specific fields. A consuming project fills in the real
field values by hand (preserved) or via factories.

Per D18 the helper ships inside the plugin. Mirrors ``enrich_test_ideas.py``:
workspace IO + error hierarchy + per-source extraction + skip-not-overwrite
accounting + CLI.

Exit codes:
    0 - test data populated.
    2 - precondition failure (uninitialized workspace, no BDD features).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from review_bdd import parse_feature_file

WORKSPACE_DIRNAME = ".test-commander"

GENERATED_MARKER = "/tc:generate-test-data"
MD_MARKER = "Generated by /tc:generate-test-data"

REQ_TAG_RE = re.compile(r"@req:(REQ-\d{3})")
CS_TAG_RE = re.compile(r"@cs:(CS-\d{3}-\d{3})")


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class GenerateTestDataError(Exception):
    pass


class UninitializedWorkspaceError(GenerateTestDataError):
    pass


class FeaturesMissingError(GenerateTestDataError):
    pass


# ---------------------------------------------------------------------------
# Data shapes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DataRecord:
    cs_id: str
    req_id: str
    scenario: str


@dataclass
class TestDataOutcome:
    area_count: int = 0
    seed_paths: list[Path] = field(default_factory=list)
    scenario_paths: list[Path] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Workspace IO
# ---------------------------------------------------------------------------


def workspace_dir(project_root: Path) -> Path:
    ws = project_root / WORKSPACE_DIRNAME
    if not ws.is_dir():
        raise UninitializedWorkspaceError(
            f"not a Test Commander workspace: {project_root} "
            f"(no {WORKSPACE_DIRNAME}/). Run /tc:init first."
        )
    return ws


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


def extract_records(feature_path: Path) -> list[DataRecord]:
    """One record per scenario carrying a resolvable @req:/@cs: linkage, sorted
    by candidate id for determinism."""
    records: list[DataRecord] = []
    for sc in parse_feature_file(feature_path):
        tags = " ".join(sc.tags)
        req = REQ_TAG_RE.search(tags)
        cs = CS_TAG_RE.search(tags)
        if not (req and cs):
            continue
        records.append(DataRecord(cs.group(1), req.group(1), sc.name))
    return sorted(records, key=lambda r: r.cs_id)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render_seed_json(area: str, records: list[DataRecord]) -> str:
    payload = {
        "_generated_by": GENERATED_MARKER,
        "area": area,
        "records": {
            r.cs_id: {
                "id": r.cs_id,
                "requirement": r.req_id,
                "label": r.scenario,
            }
            for r in records
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_scenarios_md(area: str, records: list[DataRecord]) -> str:
    lines: list[str] = []
    lines.append(f"# Test data - {area}")
    lines.append("")
    lines.append(f"_{MD_MARKER}. Declarative data requirements per scenario._")
    lines.append("")
    lines.append("| candidate | requirement | scenario | data needed |")
    lines.append("| --- | --- | --- | --- |")
    need = "(define the records this scenario needs)"
    for r in records:
        lines.append(f"| {r.cs_id} | {r.req_id} | {r.scenario} | {need} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Skip-not-overwrite write
# ---------------------------------------------------------------------------


def _write_generated(path: Path, content: str, marker: str, outcome: TestDataOutcome) -> bool:
    """Write a generated file, but never clobber a user-authored one.

    A file is user-authored if it exists and does not contain ``marker``; such a
    file is skipped (and recorded). Returns True if written."""
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if marker not in existing:
            outcome.skipped.append(str(path.name))
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def generate_test_data(project_root: Path) -> TestDataOutcome:
    workspace = workspace_dir(project_root)
    features_dir = workspace / "bdd" / "features"
    feats = sorted(features_dir.glob("*.feature")) if features_dir.is_dir() else []
    if not feats:
        raise FeaturesMissingError(
            "no feature files found under bdd/features/. "
            "Run /tc:generate-bdd first."
        )

    seed_dir = workspace / "test-data" / "seed"
    scenarios_dir = workspace / "test-data" / "scenarios"
    outcome = TestDataOutcome()
    for feature_path in feats:
        area = feature_path.stem
        records = extract_records(feature_path)
        if not records:
            continue
        seed_file = seed_dir / f"{area}.json"
        if _write_generated(
            seed_file, render_seed_json(area, records), GENERATED_MARKER, outcome
        ):
            outcome.seed_paths.append(seed_file)
        scenario_file = scenarios_dir / f"{area}.md"
        if _write_generated(
            scenario_file, render_scenarios_md(area, records), MD_MARKER, outcome
        ):
            outcome.scenario_paths.append(scenario_file)
        outcome.area_count += 1
    return outcome


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Populate test-data/ from the BDD scenarios: a JSON seed fixture and "
            "a Markdown data spec per @area:. Skip-not-overwrite for "
            "user-authored files."
        ),
    )
    parser.add_argument(
        "project_root", nargs="?", default=".",
        help="Project root (default: current directory).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    project_root = Path(args.project_root).resolve()

    try:
        outcome = generate_test_data(project_root)
    except UninitializedWorkspaceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except FeaturesMissingError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(
        f"test-data: {outcome.area_count} area(s) "
        f"({len(outcome.seed_paths)} seed file(s), skipped {len(outcome.skipped)})"
    )
    for path in outcome.seed_paths:
        print(f"  - {path.relative_to(project_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
