#!/usr/bin/env python3
"""Shared traceability-map renderers - Phase 5 Step 5.4 extraction.

Factored out of ``requirements_coverage.py`` so ``/tc:requirements-coverage``
(Phase 2) and ``/tc:traceability-map`` (Phase 5) render the requirements map
identically (DRY; no format drift). ``requirements-map.md`` is byte-identical
whichever helper wrote it.

This module imports nothing project-local so it can be reused without circular
imports. Both renderers take plain data (lists/tuples), never caller-specific
dataclasses.

- ``render_requirements_map`` - the shared 4-column requirement -> downstream
  map (REQ-ID / Test ideas / BDD features / Automation).
- ``render_test_map`` - the Phase-5 scenario-level chain with ``pending``
  downstream links (Requirement / Test idea / BDD scenario / Automated test /
  Test result / Quality report).
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

REQUIREMENTS_MAP_TITLE = "# Requirements Map"
REQUIREMENTS_MAP_INTRO = (
    "Cross-references each parsed requirement to the downstream artifacts that "
    "trace back to it. Generated by Test Commander (`/tc:requirements-coverage` "
    "and `/tc:traceability-map`); overwritten on every run."
)

TEST_MAP_TITLE = "# Test Map"
TEST_MAP_INTRO = (
    "Scenario-level traceability: each BDD scenario traced from its requirement "
    "and candidate test idea forward through the chain. Generated by "
    "`/tc:traceability-map`; overwritten on every run. Downstream links render "
    "`pending` until Phase 6 (automated tests) and Phase 7 (results, quality "
    "report) populate them."
)


def format_cell(paths: Sequence[str]) -> str:
    """Render a list of artifact paths as a single Markdown table cell."""
    if not paths:
        return "_(none)_"
    return "<br>".join(f"`{p}`" for p in paths)


def render_requirements_map(
    req_ids: Sequence[str],
    rows: Sequence[tuple[str, Sequence[str], Sequence[str], Sequence[str]]],
) -> str:
    """Render the shared requirements map.

    ``rows`` is a sequence of ``(req_id, test_ideas, bdd_features, automation)``.
    Used identically by both ``requirements_coverage`` and ``traceability_map``.
    """
    out = [REQUIREMENTS_MAP_TITLE, "", REQUIREMENTS_MAP_INTRO, ""]
    if not req_ids:
        out.append("_Inventory is empty._")
        out.append("")
        return "\n".join(out)

    out.append("| REQ-ID | Test ideas | BDD features | Automation |")
    out.append("| --- | --- | --- | --- |")
    for req_id, test_ideas, bdd_features, automation in rows:
        out.append(
            f"| {req_id} | {format_cell(test_ideas)} | "
            f"{format_cell(bdd_features)} | {format_cell(automation)} |"
        )
    out.append("")
    return "\n".join(out)


@dataclass(frozen=True)
class TestMapRow:
    req_id: str
    cs_id: str
    scenario: str
    feature: str


def render_test_map(rows: Sequence[TestMapRow]) -> str:
    """Render the Phase-5 scenario-level test map with pending downstream links."""
    out = [TEST_MAP_TITLE, "", TEST_MAP_INTRO, ""]
    if not rows:
        out.append("_No BDD scenarios with linkage tags found._")
        out.append("")
        return "\n".join(out)

    out.append(
        "| Requirement | Test idea | BDD scenario | Automated test | "
        "Test result | Quality report |"
    )
    out.append("| --- | --- | --- | --- | --- | --- |")
    for r in rows:
        out.append(
            f"| {r.req_id} | {r.cs_id} | `{r.feature}` :: {r.scenario} | "
            f"pending | pending | pending |"
        )
    out.append("")
    return "\n".join(out)
