"""Step 4.3 - /tc:explore end-to-end tests.

Drives explore.py against a tmp consuming project seeded with: (a) a
Phase 3 product-knowledge state so /tc:create-charter doesn't refuse,
(b) a CH-001 charter generated by /tc:create-charter against the same
target as the seeded fixture's charter.md, (c) a copy of the seeded
recorded-session.json placed at the configured recorded-path. Asserts:

- uninitialized workspace refused;
- missing charter refused with a precondition error pointing at
  ``/tc:create-charter``;
- missing recording refused with a precondition error pointing at the
  configured recorded path;
- seeded fixture generates ``exploration-notes/<SESS-ID>.md`` with the
  expected structure (Observations table + Anomalies summary + Evidence
  index + Charter-Coverage matrix);
- every required event type (page_load, click, fill, screenshot,
  console_message, network_request) is extracted and surfaces in the
  Observations table;
- every universal anomaly category (slow-response, console-error,
  broken-link, missing-evidence, auth-mismatch, unexpected-state)
  surfaces in the Anomalies summary;
- Evidence index lists every screenshot;
- at least one acceptance criterion is marked ``partial`` in the
  Charter-Coverage matrix (the seeded coverage shortfall - AC5
  about session expiration);
- the ``missing-evidence`` gap signal routes to
  ``requirements/open-questions.md`` with the ``[exploration-review]``
  prefix for the seeded anomaly that has ``screenshot_id: null`` AND
  no screenshot event within ±3s;
- ``--no-review`` suppresses the review sub-mode (no
  ``[exploration-review]`` gap signals appended);
- ``tc-explore.mode: live`` is refused under pytest with the same
  ``LiveModeRefusedError`` shape established in Phase 3 Step 3.5;
- idempotent re-run produces byte-identical exploration note;
- ``tc-explore.exploration.recorded-path`` config extension points the
  helper at a custom recording location;
- session IDs follow the ``SESS-YYYYMMDD-NNN`` format.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HELPER = REPO / "plugins" / "test-commander" / "scripts" / "explore.py"
INIT = REPO / "plugins" / "test-commander" / "scripts" / "init_workspace.py"
CHARTER_HELPER = REPO / "plugins" / "test-commander" / "scripts" / "create_charter.py"
FIXTURE_DIR = REPO / "tests" / "fixtures" / "seeded-exploration-session"
FIXTURE_RECORDED_SESSION = FIXTURE_DIR / "recorded-session.json"

# Charter target string used in the helper invocation. Must match the
# seeded charter.md's target verbatim so the auto-suggested coverage
# heuristic operates against the right ACs.
CHARTER_TARGET = (
    "Sign-in flow plus workspace-detail asset upload (POST /workspaces/{id}/assets)."
)

SESSION_ID_RE = re.compile(r"^SESS-\d{8}-\d{3}$")


# ---------------------------------------------------------------------------
# CLI + setup helpers
# ---------------------------------------------------------------------------


def run_init(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True,
        text=True,
        check=True,
    )


def run_helper(
    project_root: Path,
    *args: str,
    expected_exit: int = 0,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(project_root), *args],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == expected_exit, (
        f"helper exited {proc.returncode} (expected {expected_exit}). "
        f"stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )
    return proc


def run_create_charter(project_root: Path, target: str) -> None:
    proc = subprocess.run(
        [sys.executable, str(CHARTER_HELPER), str(project_root), "--target", target],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"create_charter failed: stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )


def workspace_file(project_root: Path, rel: str) -> Path:
    return project_root / ".test-commander" / rel


def seed_minimal_phase_3_state(project_root: Path) -> None:
    """Populate enough product-knowledge state for create_charter to satisfy
    its precondition check (mirrors the helper in test_create_charter.py)."""
    workspace = project_root / ".test-commander"
    pk = workspace / "product-knowledge"
    pk.mkdir(parents=True, exist_ok=True)

    (pk / "entities.md").write_text(
        "# Entities\n\n## From documents\n\n"
        "- **Account** (file:1)\n"
        "- **Workspace** (file:2)\n"
        "- **Session** (file:3)\n",
        encoding="utf-8",
    )
    (pk / "user-journeys.md").write_text(
        "# User Journeys\n\n## From documents\n\n"
        "- **Sign in and open a workspace** (file:1) - 7 steps\n",
        encoding="utf-8",
    )
    (pk / "system-model.md").write_text(
        "# System Model\n\n## Sources ingested\n\n"
        "- **documents** - via `/tc:learn-from-docs`.\n",
        encoding="utf-8",
    )

    open_q = workspace / "requirements" / "open-questions.md"
    open_q.parent.mkdir(parents=True, exist_ok=True)
    open_q.write_text("# Open questions\n\n", encoding="utf-8")


def seed_for_explore(project_root: Path, *, target: str = CHARTER_TARGET) -> Path:
    """Set up workspace with charter + recorded session at the default path."""
    run_init(project_root)
    seed_minimal_phase_3_state(project_root)
    run_create_charter(project_root, target)

    recorded_dir = workspace_file(project_root, "documents/uploaded/recorded-sessions")
    recorded_dir.mkdir(parents=True, exist_ok=True)
    target_file = recorded_dir / "CH-001.json"
    shutil.copy(FIXTURE_RECORDED_SESSION, target_file)
    return target_file


def find_session_note(project_root: Path) -> Path:
    notes_dir = workspace_file(project_root, "exploration-notes")
    matches = list(notes_dir.glob("SESS-*.md"))
    assert matches, f"expected an exploration note under {notes_dir}; found none"
    assert len(matches) == 1, f"expected exactly one session note; found {len(matches)}"
    return matches[0]


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_helper_file_exists() -> None:
    assert HELPER.is_file(), f"missing helper: {HELPER.relative_to(REPO)}"


def test_uninitialized_workspace_refused(tmp_path: Path) -> None:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(tmp_path), "--charter", "CH-001"],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2, proc.stderr


def test_missing_charter_refused(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    # No charter created. Run /tc:explore - should refuse.
    proc = run_helper(tmp_path, "--charter", "CH-001", expected_exit=2)
    stderr_lower = proc.stderr.lower()
    assert "charter" in stderr_lower
    assert "/tc:create-charter" in proc.stderr


def test_missing_recording_refused(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_create_charter(tmp_path, CHARTER_TARGET)
    # Charter exists but no recording at the default path.
    proc = run_helper(tmp_path, "--charter", "CH-001", expected_exit=2)
    stderr_lower = proc.stderr.lower()
    assert "recorded" in stderr_lower or "recording" in stderr_lower


# ---------------------------------------------------------------------------
# Happy path: seeded fixture replay
# ---------------------------------------------------------------------------


def test_seeded_recording_generates_session_note(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    proc = run_helper(tmp_path, "--charter", "CH-001")
    session_note = find_session_note(tmp_path)
    assert session_note.is_file()
    assert SESSION_ID_RE.match(session_note.stem), (
        f"session ID must match SESS-YYYYMMDD-NNN; got {session_note.stem}"
    )
    # CLI announces success.
    stdout_lower = proc.stdout.lower()
    assert "exploration" in stdout_lower or "session" in stdout_lower


def test_session_note_has_required_sections(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    for heading in (
        "# ",  # title heading
        "## Observations",
        "## Anomalies",
        "## Evidence",
        "## Charter Coverage",
    ):
        assert heading in note_text, f"session note missing required heading: {heading!r}"


def test_every_event_type_extracted(tmp_path: Path) -> None:
    """Every required event type from the seeded recording surfaces in
    the Observations table."""
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    for event_type in (
        "page_load",
        "click",
        "fill",
        "screenshot",
        "console_message",
        "network_request",
    ):
        assert event_type in note_text, (
            f"Observations table must capture event type {event_type!r}"
        )


def test_every_anomaly_category_surfaced(tmp_path: Path) -> None:
    """Every universal anomaly category from the seeded recording surfaces
    in the Anomalies summary."""
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    for category in (
        "slow-response",
        "console-error",
        "broken-link",
        "missing-evidence",
        "auth-mismatch",
        "unexpected-state",
    ):
        assert category in note_text, (
            f"Anomalies summary must capture category {category!r}"
        )


def test_evidence_index_lists_screenshots(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    # Seeded recording has S-001 through S-009.
    for screenshot_id in ("S-001", "S-002", "S-005", "S-009"):
        assert screenshot_id in note_text, (
            f"Evidence index must list screenshot {screenshot_id}"
        )
    # The Evidence index references screenshot file paths under
    # evidence/screenshots/<id>.png so the internal review sub-mode can
    # verify citation presence.
    assert "evidence/screenshots/" in note_text


# ---------------------------------------------------------------------------
# Charter-coverage matrix
# ---------------------------------------------------------------------------


def test_charter_coverage_matrix_present(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    # Coverage matrix renders each AC with one of three verdicts:
    # observed / partial / unobserved.
    assert "observed" in note_text.lower()
    # There must be at least one verdict-bearing row.
    assert re.search(
        r"\b(observed|partial|unobserved)\b", note_text, flags=re.IGNORECASE,
    ), "Charter-Coverage matrix must mark each AC with a verdict"


def test_charter_coverage_marks_partial(tmp_path: Path) -> None:
    """The seeded charter's AC about session expiration is not actually
    covered by the seeded recording (the events never trigger an actual
    session expiration; only a sign-out attempt). The coverage assessor
    should mark this AC as ``partial`` because /sign-in is reachable
    but the trigger word ``expiration`` is not observed."""
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note_text = find_session_note(tmp_path).read_text(encoding="utf-8")
    assert "partial" in note_text.lower(), (
        "at least one acceptance criterion must be marked 'partial' "
        "for the seeded coverage shortfall (AC5 about session expiration)"
    )


# ---------------------------------------------------------------------------
# Gap signals + review sub-mode
# ---------------------------------------------------------------------------


def test_missing_evidence_gap_routes_to_open_questions(tmp_path: Path) -> None:
    """The seeded recording has one anomaly with screenshot_id: null and
    no screenshot event within ±3s of its timestamp. The review sub-mode
    should emit a [exploration-review] gap signal naming missing-evidence."""
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    open_q = workspace_file(tmp_path, "requirements/open-questions.md").read_text(
        encoding="utf-8"
    )
    lowered = open_q.lower()
    assert "[exploration-review]" in lowered
    assert "missing-evidence" in lowered or "missing evidence" in lowered


def test_no_review_suppresses_review_sub_mode(tmp_path: Path) -> None:
    """The --no-review flag suppresses the review sub-mode entirely; no
    [exploration-review] gap signals should be appended."""
    seed_for_explore(tmp_path)
    # Snapshot open-questions before the run.
    open_q_path = workspace_file(tmp_path, "requirements/open-questions.md")
    pre = open_q_path.read_text(encoding="utf-8") if open_q_path.is_file() else ""

    run_helper(tmp_path, "--charter", "CH-001", "--no-review")
    post = open_q_path.read_text(encoding="utf-8")
    # The session note is still written.
    find_session_note(tmp_path)
    # No new [exploration-review] entries.
    assert "[exploration-review]" not in post.lower(), (
        "--no-review must suppress every [exploration-review] open-question append"
    )
    # Pre-existing content is preserved.
    assert post.startswith(pre[: min(len(pre), 50)])


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


def test_idempotent_rerun_byte_identical(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    first_note = find_session_note(tmp_path).read_bytes()
    first_open_q = workspace_file(tmp_path, "requirements/open-questions.md").read_text(
        encoding="utf-8"
    )

    run_helper(tmp_path, "--charter", "CH-001")
    second_note = find_session_note(tmp_path).read_bytes()
    second_open_q = workspace_file(tmp_path, "requirements/open-questions.md").read_text(
        encoding="utf-8"
    )

    assert first_note == second_note, (
        "exploration note must be byte-identical on re-run against the same recording"
    )
    assert first_open_q.count("\n") == second_open_q.count("\n"), (
        "open-questions.md line count must be stable across re-runs (dedup contract)"
    )


# ---------------------------------------------------------------------------
# Live-mode refusal under pytest
# ---------------------------------------------------------------------------


def test_live_mode_refused_under_pytest(tmp_path: Path) -> None:
    """tc-explore.mode: live must refuse when PYTEST_CURRENT_TEST is set
    so no MCP connection or browser launch leaks from the suite."""
    seed_for_explore(tmp_path)
    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-explore:\n  exploration:\n    mode: live\n"
          "    mcp-endpoint: \"http://localhost:9999\"\n"
          "    target-url: \"http://localhost:8000\"\n",
        encoding="utf-8",
    )
    proc = run_helper(tmp_path, "--charter", "CH-001", expected_exit=2)
    stderr_lower = proc.stderr.lower()
    assert "live mode" in stderr_lower or "refused" in stderr_lower


# ---------------------------------------------------------------------------
# Config extensions
# ---------------------------------------------------------------------------


def test_recorded_path_extension_applied(tmp_path: Path) -> None:
    """tc-explore.exploration.recorded-path overrides the default
    documents/uploaded/recorded-sessions/<CH-ID>.json path."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_create_charter(tmp_path, CHARTER_TARGET)

    # Place recording at a non-default path.
    custom_dir = workspace_file(tmp_path, "fixtures/recordings")
    custom_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURE_RECORDED_SESSION, custom_dir / "CH-001.json")

    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-explore:\n  exploration:\n"
          "    recorded-path: fixtures/recordings\n",
        encoding="utf-8",
    )
    run_helper(tmp_path, "--charter", "CH-001")
    # Session note exists - the helper found the recording at the custom path.
    find_session_note(tmp_path)


def test_session_id_format(tmp_path: Path) -> None:
    seed_for_explore(tmp_path)
    run_helper(tmp_path, "--charter", "CH-001")
    note = find_session_note(tmp_path)
    assert SESSION_ID_RE.match(note.stem), (
        f"session ID {note.stem!r} must match SESS-YYYYMMDD-NNN"
    )
