"""Step 4.5 - /tc:test-ideas (enrich_test_ideas) end-to-end tests.

Drives ``enrich_test_ideas.py`` against a tmp consuming project seeded
with: (a) the Phase 3 product-knowledge minimum needed for /tc:create-charter
to succeed, (b) a CH-001 charter generated by /tc:create-charter, (c) the
seeded exploration recording driven through /tc:explore, (d) the resulting
session summary written by /tc:session-summary, AND (e) the Phase 2 flawed-
requirements fixture passed through /tc:review-requirements + /tc:requirements-
to-tests so seeded test-idea files exist at ``<workspace>/test-ideas/REQ-NNN.md``.

Asserts every contract item enumerated in planning/plan.md Step 4.5:

- uninitialized workspace refused;
- missing session summaries refused with a precondition error pointing at
  ``/tc:session-summary``;
- missing test-idea seeds refused with a precondition error pointing at
  ``/tc:requirements-to-tests``;
- seeded fixture enriches **at least 3** Phase-2 test-ideas with session-
  derived candidate scenarios (per the Step 4.5 verification contract);
- every Phase-2 frontmatter key the seed shipped with is present byte-for-
  byte after enrichment (no key missing, no value mutated);
- ``status: seed`` flips to ``status: enriched`` only on enriched files;
- unenriched files remain ``status: seed`` and carry no ``phase_4_sessions:``
  or ``## Phase 4 enrichment`` section;
- ``phase_4_sessions:`` list contains the contributing SESS-IDs, sorted and
  deduplicated;
- idempotent re-run is byte-identical AND produces zero duplicate enrichment
  sections;
- a user-edited body section added between enrichment runs is preserved;
- when two sessions enrich the same REQ, ``phase_4_sessions:`` carries both
  SESS-IDs sorted and the body has one ``## Phase 4 enrichment`` section
  per session (or one section with per-session sub-blocks).
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "plugins" / "test-commander" / "scripts"
HELPER = SCRIPTS / "enrich_test_ideas.py"
INIT = SCRIPTS / "init_workspace.py"
CHARTER_HELPER = SCRIPTS / "create_charter.py"
EXPLORE_HELPER = SCRIPTS / "explore.py"
SESSION_SUMMARY_HELPER = SCRIPTS / "session_summary.py"

FIXTURE_DIR = REPO / "tests" / "fixtures" / "seeded-exploration-session"
FIXTURE_RECORDED_SESSION = FIXTURE_DIR / "recorded-session.json"
FLAWED_DIR = REPO / "tests" / "fixtures" / "seeded-flawed-requirements"
FLAWED_REQUIREMENTS = FLAWED_DIR / "requirements.md"

CHARTER_TARGET = (
    "Sign-in flow plus workspace-detail asset upload (POST /workspaces/{id}/assets)."
)

SESSION_ID_RE = re.compile(r"^SESS-\d{8}-\d{3}$")

# Phase-2 frontmatter contract -- the exact keys the Phase 2 seed ships.
# Mirrors the per-line emission order in requirements_to_tests._seed_content.
PHASE_2_FRONTMATTER_KEYS: tuple[str, ...] = (
    "schema",
    "requirement_id",
    "requirement_title",
    "source",
    "status",
    "ac_review_present",
    "phase_2_findings",
    "candidates",
    "generated_by",
)


# ---------------------------------------------------------------------------
# Helper invocation
# ---------------------------------------------------------------------------


def run_init(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True,
        text=True,
        check=True,
    )


def run_helper(
    project_root: Path,
    *args: str,
    expected_exit: int = 0,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(project_root), *args],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == expected_exit, (
        f"helper exited {proc.returncode} (expected {expected_exit}). "
        f"stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )
    return proc


def run_create_charter(project_root: Path, target: str) -> None:
    proc = subprocess.run(
        [sys.executable, str(CHARTER_HELPER), str(project_root), "--target", target],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"create_charter failed: stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )


def run_explore(project_root: Path, charter_id: str) -> None:
    proc = subprocess.run(
        [
            sys.executable,
            str(EXPLORE_HELPER),
            str(project_root),
            "--charter",
            charter_id,
        ],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"explore failed: stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )


def run_session_summary(project_root: Path, session_id: str) -> None:
    proc = subprocess.run(
        [
            sys.executable,
            str(SESSION_SUMMARY_HELPER),
            str(project_root),
            "--session",
            session_id,
        ],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"session_summary failed: stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )


def workspace_file(project_root: Path, rel: str) -> Path:
    return project_root / ".test-commander" / rel


def seed_minimal_phase_3_state(project_root: Path) -> None:
    workspace = project_root / ".test-commander"
    pk = workspace / "product-knowledge"
    pk.mkdir(parents=True, exist_ok=True)
    (pk / "entities.md").write_text(
        "# Entities\n\n## From documents\n\n"
        "- **Account** (file:1)\n"
        "- **Workspace** (file:2)\n",
        encoding="utf-8",
    )
    (pk / "user-journeys.md").write_text(
        "# User Journeys\n\n## From documents\n\n"
        "- **Sign in and open a workspace** (file:1) - 7 steps\n",
        encoding="utf-8",
    )
    (pk / "system-model.md").write_text(
        "# System Model\n\n## Sources ingested\n\n"
        "- **documents** - via `/tc:learn-from-docs`.\n",
        encoding="utf-8",
    )
    open_q = workspace / "requirements" / "open-questions.md"
    open_q.parent.mkdir(parents=True, exist_ok=True)
    open_q.write_text("# Open questions\n\n", encoding="utf-8")


def seed_phase_2_test_ideas(project_root: Path) -> None:
    """Run the Phase 2 pipeline on the flawed-requirements fixture so
    `<workspace>/test-ideas/REQ-NNN.md` files exist as Phase 4's input."""
    workspace = project_root / ".test-commander"
    uploaded = workspace / "documents" / "uploaded"
    uploaded.mkdir(parents=True, exist_ok=True)
    shutil.copy(FLAWED_REQUIREMENTS, uploaded / FLAWED_REQUIREMENTS.name)
    # Import the Phase 2 helpers directly (they are pure Python and
    # already used by tests/test_requirements_to_tests.py).
    sys.path.insert(0, str(SCRIPTS))
    try:
        import requirements_to_tests
        import review_requirements

        review_requirements.review(project_root)
        requirements_to_tests.to_tests(project_root)
    finally:
        if str(SCRIPTS) in sys.path:
            sys.path.remove(str(SCRIPTS))


def seed_full_pipeline(project_root: Path) -> str:
    """End-to-end setup: workspace + Phase 3 stub + charter + explore +
    session-summary + Phase 2 test-idea seeds. Returns the SESS-ID."""
    run_init(project_root)
    seed_minimal_phase_3_state(project_root)
    run_create_charter(project_root, CHARTER_TARGET)
    recorded_dir = workspace_file(project_root, "documents/uploaded/recorded-sessions")
    recorded_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURE_RECORDED_SESSION, recorded_dir / "CH-001.json")
    run_explore(project_root, "CH-001")
    notes = list(workspace_file(project_root, "exploration-notes").glob("SESS-*.md"))
    assert len(notes) == 1, f"expected exactly one exploration note; got {len(notes)}"
    session_id = notes[0].stem
    run_session_summary(project_root, session_id)
    seed_phase_2_test_ideas(project_root)
    return session_id


# ---------------------------------------------------------------------------
# Lightweight frontmatter parser (test-side; mirrors producer contract)
# ---------------------------------------------------------------------------


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_body, post_frontmatter_body). Frontmatter is the
    YAML-ish block delimited by the first and second ``---`` lines."""
    assert text.startswith("---\n"), "test-idea seed must begin with --- frontmatter"
    end = text.find("\n---\n", 4)
    assert end > 0, "frontmatter must end with --- delimiter"
    return text[4:end], text[end + len("\n---\n") :]


def frontmatter_top_level_keys(fm: str) -> list[str]:
    """Return the top-level YAML keys in encounter order."""
    keys: list[str] = []
    for line in fm.split("\n"):
        m = re.match(r"^([a-z][a-z0-9_-]*):", line)
        if m:
            keys.append(m.group(1))
    return keys


def frontmatter_scalar(fm: str, key: str) -> str | None:
    """Return the trimmed scalar value for ``key`` if it appears as a
    single-line ``key: value`` entry; else None."""
    for line in fm.split("\n"):
        m = re.match(rf"^{re.escape(key)}:\s*(.*?)\s*$", line)
        if m:
            return m.group(1)
    return None


def list_enriched_files(project_root: Path) -> list[Path]:
    test_ideas = workspace_file(project_root, "test-ideas")
    return [
        p
        for p in sorted(test_ideas.glob("REQ-*.md"))
        if "## Phase 4 enrichment" in p.read_text(encoding="utf-8")
    ]


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_helper_file_exists() -> None:
    assert HELPER.is_file(), f"missing helper: {HELPER.relative_to(REPO)}"


def test_uninitialized_workspace_refused(tmp_path: Path) -> None:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2, proc.stderr
    assert "workspace" in proc.stderr.lower() or "init" in proc.stderr.lower()


def test_missing_session_summaries_refused(tmp_path: Path) -> None:
    """Workspace is initialized but no session summaries exist. The helper
    must refuse with a precondition error directing the user at
    ``/tc:session-summary``."""
    run_init(tmp_path)
    seed_phase_2_test_ideas(tmp_path)
    proc = run_helper(tmp_path, expected_exit=2)
    assert "session" in proc.stderr.lower()
    assert "/tc:session-summary" in proc.stderr


def test_missing_test_idea_seeds_refused(tmp_path: Path) -> None:
    """Workspace is initialized and a session summary exists, but no
    test-idea seeds. The helper must refuse with a precondition error
    directing the user at ``/tc:requirements-to-tests``."""
    session_id = seed_full_pipeline(tmp_path)
    # Wipe the seeded test-ideas to simulate the "seeds missing" state.
    test_ideas = workspace_file(tmp_path, "test-ideas")
    for p in test_ideas.glob("REQ-*.md"):
        p.unlink()
    proc = run_helper(tmp_path, "--session", session_id, expected_exit=2)
    assert "test-idea" in proc.stderr.lower() or "test idea" in proc.stderr.lower()
    assert "/tc:requirements-to-tests" in proc.stderr


# ---------------------------------------------------------------------------
# Happy path: seeded session enriches at least three REQ test-ideas
# ---------------------------------------------------------------------------


def test_enriches_at_least_three_test_ideas(tmp_path: Path) -> None:
    """Per the Step 4.5 verification contract: the smoke run must enrich
    at least three Phase-2-seeded test-ideas with session-derived
    candidate scenarios."""
    session_id = seed_full_pipeline(tmp_path)
    proc = run_helper(tmp_path, "--session", session_id)
    enriched = list_enriched_files(tmp_path)
    assert len(enriched) >= 3, (
        f"expected >= 3 enriched test-ideas; got {len(enriched)} "
        f"(stdout: {proc.stdout!r})"
    )


def test_enriched_files_carry_phase_4_section(tmp_path: Path) -> None:
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    for path in list_enriched_files(tmp_path):
        text = path.read_text(encoding="utf-8")
        assert "## Phase 4 enrichment" in text, (
            f"enriched file {path.name} missing the Phase 4 section"
        )
        # The session must be cited in the enrichment body.
        assert session_id in text, (
            f"enriched file {path.name} does not cite SESS-ID {session_id}"
        )


def test_unenriched_files_unchanged(tmp_path: Path) -> None:
    """Files that are NOT enriched must keep ``status: seed`` and carry no
    ``phase_4_sessions:`` or ``## Phase 4 enrichment`` body section."""
    session_id = seed_full_pipeline(tmp_path)
    # Snapshot the seeded REQ files BEFORE enrichment.
    test_ideas = workspace_file(tmp_path, "test-ideas")
    pre_snapshot: dict[str, str] = {}
    for p in sorted(test_ideas.glob("REQ-*.md")):
        pre_snapshot[p.name] = p.read_text(encoding="utf-8")

    run_helper(tmp_path, "--session", session_id)

    enriched_names = {p.name for p in list_enriched_files(tmp_path)}
    for name, original in pre_snapshot.items():
        if name in enriched_names:
            continue
        current = (test_ideas / name).read_text(encoding="utf-8")
        assert current == original, (
            f"unenriched file {name} was mutated; helper must leave non-matching "
            "seeds byte-identical"
        )


# ---------------------------------------------------------------------------
# Phase-2 frontmatter contract preservation
# ---------------------------------------------------------------------------


def test_frontmatter_keys_preserved_byte_for_byte(tmp_path: Path) -> None:
    """For every enriched file, every Phase-2 frontmatter key must still
    be present after enrichment with its original value -- except
    ``status:`` which flips ``seed`` -> ``enriched``."""
    session_id = seed_full_pipeline(tmp_path)
    test_ideas = workspace_file(tmp_path, "test-ideas")
    pre_snapshot: dict[str, str] = {}
    for p in sorted(test_ideas.glob("REQ-*.md")):
        pre_snapshot[p.name] = p.read_text(encoding="utf-8")

    run_helper(tmp_path, "--session", session_id)

    enriched_paths = list_enriched_files(tmp_path)
    assert enriched_paths, "at least one file must be enriched for this test to matter"
    for path in enriched_paths:
        original_fm, _ = split_frontmatter(pre_snapshot[path.name])
        new_fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        original_keys = frontmatter_top_level_keys(original_fm)
        new_keys = frontmatter_top_level_keys(new_fm)
        for key in original_keys:
            assert key in new_keys, (
                f"{path.name}: frontmatter key {key!r} disappeared after enrichment"
            )
        # Every Phase-2 contract key the seed shipped with must still exist.
        for key in PHASE_2_FRONTMATTER_KEYS:
            if key in original_keys:
                assert key in new_keys, (
                    f"{path.name}: Phase-2 contract key {key!r} missing post-enrich"
                )
        # Scalar values must be byte-identical for every preserved key
        # other than ``status:``.
        preserved_scalars = ("schema", "requirement_id", "requirement_title",
                             "source", "ac_review_present", "generated_by")
        for key in preserved_scalars:
            orig = frontmatter_scalar(original_fm, key)
            curr = frontmatter_scalar(new_fm, key)
            if orig is not None:
                assert curr == orig, (
                    f"{path.name}: scalar {key!r} value mutated "
                    f"({orig!r} -> {curr!r})"
                )


def test_status_flips_on_enriched_only(tmp_path: Path) -> None:
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    test_ideas = workspace_file(tmp_path, "test-ideas")
    enriched_names = {p.name for p in list_enriched_files(tmp_path)}
    for path in sorted(test_ideas.glob("REQ-*.md")):
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        status = frontmatter_scalar(fm, "status")
        if path.name in enriched_names:
            assert status == "enriched", (
                f"{path.name}: enriched file must carry status: enriched (got {status!r})"
            )
        else:
            assert status == "seed", (
                f"{path.name}: non-enriched file must keep status: seed (got {status!r})"
            )


def test_phase_4_sessions_populated_and_sorted(tmp_path: Path) -> None:
    """``phase_4_sessions:`` must be a YAML inline list containing the
    contributing SESS-IDs, sorted and deduplicated."""
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    for path in list_enriched_files(tmp_path):
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        sessions_line = frontmatter_scalar(fm, "phase_4_sessions")
        assert sessions_line is not None, (
            f"{path.name}: enriched file missing phase_4_sessions: key"
        )
        # Inline list: ``[SESS-..., ...]``.
        assert sessions_line.startswith("[") and sessions_line.endswith("]"), (
            f"{path.name}: phase_4_sessions must be inline list (got {sessions_line!r})"
        )
        ids = [s.strip() for s in sessions_line.strip("[]").split(",") if s.strip()]
        assert session_id in ids, (
            f"{path.name}: phase_4_sessions does not include {session_id}"
        )
        assert ids == sorted(set(ids)), (
            f"{path.name}: phase_4_sessions not sorted-deduplicated ({ids})"
        )


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


def test_idempotent_rerun_byte_identical(tmp_path: Path) -> None:
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    test_ideas = workspace_file(tmp_path, "test-ideas")
    first: dict[str, bytes] = {
        p.name: p.read_bytes() for p in sorted(test_ideas.glob("REQ-*.md"))
    }
    run_helper(tmp_path, "--session", session_id)
    second: dict[str, bytes] = {
        p.name: p.read_bytes() for p in sorted(test_ideas.glob("REQ-*.md"))
    }
    assert first == second, (
        "all test-idea files must be byte-identical on idempotent re-run"
    )


def test_idempotent_rerun_no_duplicate_enrichment_sections(tmp_path: Path) -> None:
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    run_helper(tmp_path, "--session", session_id)
    for path in list_enriched_files(tmp_path):
        text = path.read_text(encoding="utf-8")
        section_count = text.count("## Phase 4 enrichment")
        assert section_count == 1, (
            f"{path.name}: expected exactly 1 '## Phase 4 enrichment' header; "
            f"got {section_count}"
        )
        # And the session sub-block must appear exactly once.
        block_count = text.count(f"### {session_id}")
        assert block_count <= 1, (
            f"{path.name}: SESS-ID sub-block duplicated on re-run "
            f"(count={block_count})"
        )


def test_user_edits_to_body_preserved(tmp_path: Path) -> None:
    """A user (or downstream phase) may add a custom section to an enriched
    test-idea between runs. Re-running enrichment must not strip it."""
    session_id = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id)
    enriched = list_enriched_files(tmp_path)
    assert enriched, "need at least one enriched file for this test"
    target = enriched[0]
    sentinel = "## User-added notes\n\nThis section was authored by hand.\n"
    with target.open("a", encoding="utf-8") as fh:
        fh.write("\n" + sentinel)
    run_helper(tmp_path, "--session", session_id)
    after = target.read_text(encoding="utf-8")
    assert sentinel.rstrip() in after, (
        f"{target.name}: user-edited section stripped on enrichment re-run"
    )


# ---------------------------------------------------------------------------
# Multi-session contract
# ---------------------------------------------------------------------------


def test_multiple_sessions_merged_into_phase_4_sessions(tmp_path: Path) -> None:
    """When two sessions enrich the same REQ, ``phase_4_sessions:`` carries
    both sorted-deduplicated, and the body has two SESS-ID sub-blocks."""
    session_id_1 = seed_full_pipeline(tmp_path)
    run_helper(tmp_path, "--session", session_id_1)

    # Synthesize a second session summary with the same charter so the
    # same charter-coverage cross-reference fires against the same REQs.
    session_id_2 = "SESS-20260528-900"
    # The second session reuses session_id_1's body (charter coverage and
    # candidates are identical) but with a different SESS-ID in the title
    # and CS prefix so dedup logic gets exercised.
    summary_1 = workspace_file(tmp_path, f"sessions/{session_id_1}.md").read_text(
        encoding="utf-8"
    )
    summary_2 = summary_1.replace(session_id_1, session_id_2)
    # Replace CS-NNN-001 etc. with the second session's prefix so candidate IDs
    # remain unique.
    nnn_1 = session_id_1.split("-")[-1]
    nnn_2 = session_id_2.split("-")[-1]
    summary_2 = re.sub(rf"CS-{nnn_1}-(\d{{3}})", rf"CS-{nnn_2}-\1", summary_2)
    workspace_file(tmp_path, f"sessions/{session_id_2}.md").write_text(
        summary_2, encoding="utf-8"
    )

    run_helper(tmp_path, "--session", session_id_2)

    enriched = list_enriched_files(tmp_path)
    assert enriched, "expected at least one file enriched by both sessions"
    # At least one file must list both SESS-IDs.
    multi_enriched = []
    for path in enriched:
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        sessions_line = frontmatter_scalar(fm, "phase_4_sessions") or ""
        ids = [s.strip() for s in sessions_line.strip("[]").split(",") if s.strip()]
        if session_id_1 in ids and session_id_2 in ids:
            multi_enriched.append((path, ids))
    assert multi_enriched, (
        "expected at least one file with both SESS-IDs in phase_4_sessions"
    )
    for path, ids in multi_enriched:
        assert ids == sorted(set(ids)), (
            f"{path.name}: phase_4_sessions not sorted-dedup ({ids})"
        )
        text = path.read_text(encoding="utf-8")
        # Per-session sub-blocks expected -- one per SESS-ID.
        assert f"### {session_id_1}" in text or session_id_1 in text
        assert f"### {session_id_2}" in text or session_id_2 in text


def test_all_sessions_default_when_no_session_flag(tmp_path: Path) -> None:
    """Without ``--session``, the helper enriches against every session
    in ``<workspace>/sessions/`` (excluding ``index.md``)."""
    session_id = seed_full_pipeline(tmp_path)
    proc = run_helper(tmp_path)
    # At least the seeded session's enrichment must land.
    enriched = list_enriched_files(tmp_path)
    assert enriched, f"no files enriched (stdout: {proc.stdout!r})"
    sample = enriched[0].read_text(encoding="utf-8")
    assert session_id in sample


# ---------------------------------------------------------------------------
# CLI surface
# ---------------------------------------------------------------------------


def test_cli_reports_enriched_count(tmp_path: Path) -> None:
    session_id = seed_full_pipeline(tmp_path)
    proc = run_helper(tmp_path, "--session", session_id)
    # The stdout must surface a count of enriched files for operator visibility.
    assert "enriched" in proc.stdout.lower() or re.search(r"\b\d+\b", proc.stdout), (
        f"CLI stdout missing enriched-count summary: {proc.stdout!r}"
    )


# ---------------------------------------------------------------------------
# Cross-phase contract enumeration (Step 4.4 lesson)
# ---------------------------------------------------------------------------


def test_candidate_shape_contract_is_declared() -> None:
    """Per the Step 4.4 lesson on three-layer contracts: the consumer
    (enrich_test_ideas) must declare a CandidateScenario dataclass whose
    fields mirror the producer (session_summary.CandidateScenario).
    Importing the consumer module must therefore expose a matching dataclass.
    """
    sys.path.insert(0, str(SCRIPTS))
    try:
        import enrich_test_ideas
        import session_summary
    finally:
        if str(SCRIPTS) in sys.path:
            sys.path.remove(str(SCRIPTS))
    producer_fields = {
        f.name for f in session_summary.CandidateScenario.__dataclass_fields__.values()
    }
    consumer_fields = {
        f.name for f in enrich_test_ideas.CandidateScenario.__dataclass_fields__.values()
    }
    assert producer_fields <= consumer_fields, (
        f"consumer CandidateScenario must mirror producer fields. "
        f"Producer: {producer_fields}; consumer: {consumer_fields}"
    )
