"""Step 3.2 - /tc:learn-from-docs end-to-end tests.

Drives extract_knowledge_from_docs.py and the shared synthesize_system_model.py
helper against the seeded-sample-project fixture (Step 3.1). Asserts:

- uninitialized workspace refused;
- no-narrative-documents path writes a stub documentation-model + system-model;
- files containing ``REQ-\\d+`` markers are skipped (Phase-2 inverse filter);
- five positive rubric dimensions extracted with file:line provenance
  (entities, terms, user-journeys, business-rules, assumptions);
- two gap signals routed to ``requirements/open-questions.md``
  (undefined-term, contradictory-rule);
- cross-cutting artifacts get a ``## From documents`` section while preserving
  any prior ``## From <other-source>`` sections;
- ``system-model.md`` regenerated by the shared synthesizer;
- idempotent re-run: byte-identical documentation-model, byte-identical
  ``## From documents`` sections, line-stable open-questions, byte-identical
  ``system-model.md``;
- ``tc-knowledge.documents.entity-keywords`` and ``journey-headings`` config
  extensions union with the universal cores additively.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
HELPER = REPO / "plugins" / "test-commander" / "scripts" / "extract_knowledge_from_docs.py"
SYNTH = REPO / "plugins" / "test-commander" / "scripts" / "synthesize_system_model.py"
INIT = REPO / "plugins" / "test-commander" / "scripts" / "init_workspace.py"
FIXTURE_DOCS = REPO / "tests" / "fixtures" / "seeded-sample-project" / "documents"


def run_init(project_root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True,
        text=True,
        check=True,
    )


def run_helper(project_root: Path, expected_exit: int = 0) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(project_root)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == expected_exit, (
        f"helper exited {proc.returncode} (expected {expected_exit}). stderr:\n{proc.stderr}"
    )
    return proc


def copy_seeded_docs(project_root: Path) -> None:
    """Copy the three seeded fixture documents into the workspace's uploaded directory."""
    uploaded = project_root / ".test-commander" / "documents" / "uploaded"
    uploaded.mkdir(parents=True, exist_ok=True)
    for name in ("product-overview.md", "glossary.md", "user-journey-sign-in.md"):
        shutil.copy(FIXTURE_DOCS / name, uploaded / name)


def workspace_file(project_root: Path, rel: str) -> Path:
    return project_root / ".test-commander" / rel


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_uninitialized_workspace_refused(tmp_path: Path):
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2, proc.stderr
    stderr_lower = proc.stderr.lower()
    assert "not a test commander workspace" in stderr_lower or ".test-commander" in proc.stderr


def test_helper_files_exist():
    assert HELPER.is_file(), f"missing helper: {HELPER.relative_to(REPO)}"
    assert SYNTH.is_file(), f"missing synthesizer: {SYNTH.relative_to(REPO)}"


# ---------------------------------------------------------------------------
# No-documents path
# ---------------------------------------------------------------------------


def test_no_narrative_documents_writes_stub_documentation_model(tmp_path: Path):
    run_init(tmp_path)
    # documents/uploaded/ is empty after init (no REQ-bearing files; no narrative files)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    assert "no narrative documents found" in doc_model.lower()


def test_no_narrative_documents_still_regenerates_system_model(tmp_path: Path):
    run_init(tmp_path)
    run_helper(tmp_path)
    system_model = workspace_file(tmp_path, "product-knowledge/system-model.md").read_text(
        encoding="utf-8"
    )
    lowered = system_model.lower()
    assert "no sources ingested" in lowered or "no source has been ingested" in lowered


def test_requirements_source_files_are_skipped(tmp_path: Path):
    """A *.md file containing REQ-NNN must NOT be treated as a narrative document."""
    run_init(tmp_path)
    uploaded = workspace_file(tmp_path, "documents/uploaded")
    uploaded.mkdir(parents=True, exist_ok=True)
    (uploaded / "fake-requirements.md").write_text(
        "# Project requirements\n\nREQ-001: The system shall greet the user.\n",
        encoding="utf-8",
    )
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    assert "no narrative documents found" in doc_model.lower()


# ---------------------------------------------------------------------------
# Seeded-fixture extraction
# ---------------------------------------------------------------------------


def test_seeded_fixture_documentation_model_lists_sources(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    for name in ("product-overview.md", "glossary.md", "user-journey-sign-in.md"):
        assert name in doc_model, f"documentation-model.md must list source {name}"


def test_seeded_fixture_extracts_entities_with_citations(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # Glossary terms become entities; at minimum Account, Workspace, Session must appear.
    for name in ("Account", "Workspace", "Session"):
        assert name in doc_model, f"entity {name} not in documentation-model.md"
    # Provenance: at least one entity line must include a file:line citation
    assert "glossary.md:" in doc_model, "entity findings must cite file:line"


def test_seeded_fixture_extracts_terms_with_definitions(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # The glossary defines Account, Session, Workspace, Asset, Permission.
    for term in ("Account", "Session", "Workspace", "Asset", "Permission"):
        assert term in doc_model
    # Definition fragments come from the glossary body.
    assert "registered" in doc_model.lower() or "platform" in doc_model.lower()


def test_seeded_fixture_extracts_user_journeys_with_steps(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # The seeded journey heading is "User journey - sign in and open a workspace".
    assert "sign in" in doc_model.lower()
    # Step count detection - the seed has at least seven numbered steps.
    assert "user-journey-sign-in.md:" in doc_model


def test_seeded_fixture_extracts_business_rules(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # At least one rule containing "must" or "shall" should surface.
    assert " must " in doc_model.lower() or " shall " in doc_model.lower()
    # Asset size rule from product-overview.md.
    assert "10 mb" in doc_model.lower() or "asset" in doc_model.lower()


def test_seeded_fixture_extracts_assumptions(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # The narrative contains "The narrative assumes that every account verifies..."
    assert "assume" in doc_model.lower()
    # Assumptions must be flagged distinctly from confirmed facts.
    assert "no direct citation" in doc_model.lower() or "assumption" in doc_model.lower()


# ---------------------------------------------------------------------------
# Gap signals
# ---------------------------------------------------------------------------


def test_undefined_term_signals_open_question(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    open_questions = workspace_file(tmp_path, "requirements/open-questions.md").read_text(
        encoding="utf-8"
    )
    # Telemetry appears in product-overview.md but never in glossary/definition list.
    assert "telemetry" in open_questions.lower(), (
        "undefined-term gap should produce an open question naming the undefined term"
    )


def test_contradictory_rule_signals_open_question(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    open_questions = workspace_file(tmp_path, "requirements/open-questions.md").read_text(
        encoding="utf-8"
    )
    # Fixture: "An admin may delete any workspace" vs "An admin must not delete a
    # workspace they did not create" - two contradictory delete-workspace rules.
    lowered = open_questions.lower()
    assert "contradict" in lowered or "conflict" in lowered, (
        "contradictory-rule gap should produce an open question describing the conflict"
    )


# ---------------------------------------------------------------------------
# Cross-cutting artifact contributions
# ---------------------------------------------------------------------------


def test_cross_cutting_entities_has_from_documents_section(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    entities = workspace_file(tmp_path, "product-knowledge/entities.md").read_text(encoding="utf-8")
    assert "## From documents" in entities
    assert "Account" in entities


def test_cross_cutting_user_journeys_has_from_documents_section(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    journeys = workspace_file(tmp_path, "product-knowledge/user-journeys.md").read_text(
        encoding="utf-8"
    )
    assert "## From documents" in journeys
    assert "sign in" in journeys.lower()


def test_cross_cutting_business_rules_has_from_documents_section(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    rules = workspace_file(tmp_path, "product-knowledge/business-rules.md").read_text(
        encoding="utf-8"
    )
    assert "## From documents" in rules


def test_cross_cutting_assumptions_has_from_documents_section(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    assumptions = workspace_file(tmp_path, "product-knowledge/assumptions.md").read_text(
        encoding="utf-8"
    )
    assert "## From documents" in assumptions


def test_cross_cutting_preserves_other_source_sections(tmp_path: Path):
    """A pre-existing '## From specs' section must survive when /tc:learn-from-docs runs."""
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    # Pre-seed entities.md with a fake `## From specs` section.
    entities_path = workspace_file(tmp_path, "product-knowledge/entities.md")
    entities_path.write_text(
        "# Entities\n\n"
        "> Cross-source entity index.\n\n"
        "## From specs\n\n- **Endpoint** — placeholder from spec source.\n",
        encoding="utf-8",
    )
    run_helper(tmp_path)
    entities = entities_path.read_text(encoding="utf-8")
    assert "## From specs" in entities, "specs section must be preserved"
    assert "Endpoint" in entities, "specs section body must be preserved"
    assert "## From documents" in entities, "documents section must be added"


# ---------------------------------------------------------------------------
# System-model synthesis
# ---------------------------------------------------------------------------


def test_system_model_reflects_docs_ingestion(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    system_model = workspace_file(tmp_path, "product-knowledge/system-model.md").read_text(
        encoding="utf-8"
    )
    lowered = system_model.lower()
    assert "documents" in lowered, "system-model must record that the documents source was ingested"
    assert "account" in lowered or "workspace" in lowered, (
        "system-model must list at least one cross-source entity"
    )


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


def test_idempotent_documentation_model_byte_identical(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    first = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_bytes()
    run_helper(tmp_path)
    second = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_bytes()
    assert first == second, "documentation-model.md must be byte-identical on re-run"


def test_idempotent_cross_cutting_byte_identical(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    snapshots = {
        name: workspace_file(tmp_path, f"product-knowledge/{name}.md").read_bytes()
        for name in ("entities", "user-journeys", "business-rules", "assumptions")
    }
    run_helper(tmp_path)
    for name, snapshot in snapshots.items():
        current = workspace_file(tmp_path, f"product-knowledge/{name}.md").read_bytes()
        assert current == snapshot, f"{name}.md must be byte-identical on re-run"


def test_idempotent_open_questions_line_stable(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    first = workspace_file(tmp_path, "requirements/open-questions.md").read_text(encoding="utf-8")
    run_helper(tmp_path)
    second = workspace_file(tmp_path, "requirements/open-questions.md").read_text(encoding="utf-8")
    assert first.count("\n") == second.count("\n"), (
        "open-questions.md line count must be stable across re-runs"
    )


def test_idempotent_system_model_byte_identical(tmp_path: Path):
    run_init(tmp_path)
    copy_seeded_docs(tmp_path)
    run_helper(tmp_path)
    first = workspace_file(tmp_path, "product-knowledge/system-model.md").read_bytes()
    run_helper(tmp_path)
    second = workspace_file(tmp_path, "product-knowledge/system-model.md").read_bytes()
    assert first == second, "system-model.md must be byte-identical on re-run"


# ---------------------------------------------------------------------------
# Config extensions
# ---------------------------------------------------------------------------


def test_entity_keywords_extension_applied(tmp_path: Path):
    """tc-knowledge.documents.entity-keywords surfaces domain terms as entities
    even when they appear only in prose, never under a glossary heading.

    The universal core matches capitalized noun phrases in glossary/entity
    sections only; the extension matcher is case-sensitive (domain entities
    are proper nouns), so this test uses an inline narrative with capitalized
    domain terms (Patient, Provider, Claim) rather than the lowercase
    common-noun mentions in the seeded fixture.
    """
    run_init(tmp_path)
    uploaded = workspace_file(tmp_path, "documents/uploaded")
    uploaded.mkdir(parents=True, exist_ok=True)
    (uploaded / "narrative.md").write_text(
        "# Domain narrative\n\n"
        "The Patient interacts with the Provider during a Claim event.\n"
        "Each Patient may file multiple Claims.\n",
        encoding="utf-8",
    )
    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-knowledge:\n"
        "  documents:\n"
        "    entity-keywords: [Patient, Provider, Claim]\n",
        encoding="utf-8",
    )
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    for term in ("Patient", "Provider", "Claim"):
        assert term in doc_model, f"entity-keywords extension must surface '{term}' as an entity"


def test_journey_headings_extension_applied(tmp_path: Path):
    """config.yaml's tc-knowledge.documents.journey-headings widens journey-section detection."""
    run_init(tmp_path)
    uploaded = workspace_file(tmp_path, "documents/uploaded")
    uploaded.mkdir(parents=True, exist_ok=True)
    (uploaded / "story.md").write_text(
        "# Sign-in story\n\n"
        "## Story\n\n"
        "1. The user opens the app.\n"
        "2. The user signs in.\n"
        "3. The user reaches the dashboard.\n",
        encoding="utf-8",
    )
    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-knowledge:\n"
        "  documents:\n"
        "    journey-headings: [story]\n",
        encoding="utf-8",
    )
    run_helper(tmp_path)
    doc_model = workspace_file(tmp_path, "product-knowledge/documentation-model.md").read_text(
        encoding="utf-8"
    )
    # Without the extension the "Story" heading would not be a journey;
    # with the extension it is.
    assert "story.md" in doc_model, (
        "journey-headings extension must surface story.md as journey source"
    )
    journeys = workspace_file(tmp_path, "product-knowledge/user-journeys.md").read_text(
        encoding="utf-8"
    )
    assert "sign-in story" in journeys.lower() or "story" in journeys.lower()


# ---------------------------------------------------------------------------
# Synthesizer direct test
# ---------------------------------------------------------------------------


def test_synthesizer_callable_standalone(tmp_path: Path):
    """synthesize_system_model.py can be invoked directly on an initialized workspace."""
    run_init(tmp_path)
    proc = subprocess.run(
        [sys.executable, str(SYNTH), str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    system_model = workspace_file(tmp_path, "product-knowledge/system-model.md").read_text(
        encoding="utf-8"
    )
    assert "system model" in system_model.lower()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
