"""Step 4.2 - /tc:create-charter end-to-end tests.

Drives create_charter.py against a tmp consuming project seeded with
minimal Phase-3 product-knowledge state. Asserts:

- uninitialized workspace refused;
- empty / template-stub product-knowledge refused with a precondition
  error directing the user at ``/tc:learn-from-docs``;
- ``--target`` argument generates a CH-001 charter with valid YAML
  frontmatter carrying every CHARTER_REQUIRED_FIELDS key (the
  cross-phase contract from Step 4.1);
- auto-suggestion (no ``--target``) picks the entity with the highest
  total mention count across product-knowledge + open-questions
  (ties broken alphabetically);
- idempotent re-run with the same ``--target`` produces
  ``created: 0, skipped: 1`` and leaves the charter byte-identical;
- ``--new-id`` flag re-allocates as CH-002 even when the target
  matches an existing charter;
- user-edited charter body is preserved across re-runs (skip-not-
  overwrite for downstream-enriched artifacts; mirrors the Phase 2
  Step 2.6 idempotency lesson);
- the rendered charter passes the internal
  ``_charter_is_well_formed`` shape check;
- ``tc-explore.charters.{risk-keywords, area-keywords}`` config
  extensions union with the universal core additively.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HELPER = REPO / "plugins" / "test-commander" / "scripts" / "create_charter.py"
INIT = REPO / "plugins" / "test-commander" / "scripts" / "init_workspace.py"


# ---------------------------------------------------------------------------
# CLI + setup helpers
# ---------------------------------------------------------------------------


def run_init(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True,
        text=True,
        check=True,
    )


def run_helper(
    project_root: Path,
    *args: str,
    expected_exit: int = 0,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(project_root), *args],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == expected_exit, (
        f"helper exited {proc.returncode} (expected {expected_exit}). "
        f"stderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )
    return proc


def workspace_file(project_root: Path, rel: str) -> Path:
    return project_root / ".test-commander" / rel


def seed_minimal_phase_3_state(
    project_root: Path,
    *,
    top_entity: str = "Workspace",
    other_entities: tuple[str, ...] = ("Account", "Session", "Asset"),
) -> None:
    """Populate enough Phase 3 product-knowledge + Phase 2 open-questions
    state for the create-charter helper to satisfy its preconditions and
    pick ``top_entity`` as the highest-mention candidate."""
    workspace = project_root / ".test-commander"
    pk = workspace / "product-knowledge"
    pk.mkdir(parents=True, exist_ok=True)

    # Cross-cutting entities.md with one entity per source. Mention
    # ``top_entity`` more often by including it across multiple sources.
    entities = ["# Entities", "", "Cross-source entity index.", ""]
    entities.append("## From documents")
    entities.append("")
    for name in (top_entity, *other_entities):
        entities.append(f"- **{name}** (documents/uploaded/glossary.md:5)")
    entities.append("")
    entities.append("## From code")
    entities.append("")
    entities.append(f"- **{top_entity}** (documents/uploaded/code/app/models/workspace.py:4)")
    entities.append("")
    (pk / "entities.md").write_text("\n".join(entities) + "\n", encoding="utf-8")

    # user-journeys.md with at least one journey.
    (pk / "user-journeys.md").write_text(
        "# User Journeys\n\n"
        "Cross-source user-journey index.\n\n"
        "## From documents\n\n"
        f"- **Sign in and open a {top_entity}** "
        f"(documents/uploaded/user-journey-sign-in.md:1-23) - 7 steps\n",
        encoding="utf-8",
    )

    # system-model.md non-stub (the synthesizer's "ingested" marker shape).
    (pk / "system-model.md").write_text(
        "# System Model\n\n"
        "Auto-generated by the `tc-knowledge` synthesizer.\n\n"
        "## Sources ingested\n\n"
        "- **documents** - via `/tc:learn-from-docs`.\n",
        encoding="utf-8",
    )

    # Phase-2 open-questions mentioning the top entity more often.
    open_questions = workspace / "requirements" / "open-questions.md"
    open_questions.parent.mkdir(parents=True, exist_ok=True)
    open_questions.write_text(
        "# Open questions\n\n"
        f"- [tc-knowledge/learn-from-docs] Bolded term '{top_entity}' is used "
        "in prose but is not defined.\n"
        f"- [tc-knowledge/learn-from-code] [undocumented-function] Function "
        f"in {top_entity}.py has no docstring.\n"
        f"- [tc-knowledge/learn-from-tests] [untested-function] Public "
        f"function in {top_entity} module is not referenced by any test.\n"
        f"- [tc-knowledge/learn-from-docs] {other_entities[0]} relationship "
        "to other entities is unclear.\n",
        encoding="utf-8",
    )

    # risk-register stub - the helper reads but tolerates empty contents.
    risk_register = workspace / "risk-register" / "risk-register.md"
    risk_register.parent.mkdir(parents=True, exist_ok=True)
    risk_register.write_text(
        "# Risk Register\n\n_(empty until populated)_\n",
        encoding="utf-8",
    )


def read_frontmatter(charter_path: Path) -> dict[str, str]:
    text = charter_path.read_text(encoding="utf-8")
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    assert m, f"missing frontmatter in {charter_path}"
    fm = m.group(1)
    result: dict[str, str] = {}
    for line in fm.split("\n"):
        if ":" not in line:
            continue
        if line.startswith(" "):
            # list-item continuation
            continue
        key, _, value = line.partition(":")
        result[key.strip()] = value.strip()
    return result


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_uninitialized_workspace_refused(tmp_path: Path) -> None:
    proc = subprocess.run(
        [sys.executable, str(HELPER), str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2, proc.stderr
    stderr_lower = proc.stderr.lower()
    assert "not a test commander workspace" in stderr_lower or ".test-commander" in proc.stderr


def test_helper_file_exists() -> None:
    assert HELPER.is_file(), f"missing helper: {HELPER.relative_to(REPO)}"


def test_product_knowledge_missing_refused(tmp_path: Path) -> None:
    """Workspace exists but Phase 3 has not yet run - product-knowledge
    artifacts are still the template stubs. The helper must refuse with
    a precondition error pointing the user at /tc:learn-from-docs."""
    run_init(tmp_path)
    proc = run_helper(tmp_path, "--target", "Sign-in flow", expected_exit=2)
    stderr_lower = proc.stderr.lower()
    assert "product-knowledge" in stderr_lower
    assert "/tc:learn-from-docs" in proc.stderr or "phase 3" in stderr_lower


# ---------------------------------------------------------------------------
# --target argument path
# ---------------------------------------------------------------------------


def test_target_argument_generates_ch_001(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    proc = run_helper(tmp_path, "--target", "Sign-in flow plus workspace asset upload")

    charter = workspace_file(tmp_path, "charters/CH-001.md")
    assert charter.is_file(), f"expected charter at {charter}; stdout:\n{proc.stdout}"
    text = charter.read_text(encoding="utf-8")
    assert text.startswith("---\n"), "charter must begin with YAML frontmatter"
    # CLI reports the creation
    stdout_lower = proc.stdout.lower()
    assert "created" in stdout_lower
    assert "CH-001" in proc.stdout


def test_target_argument_populates_required_frontmatter_fields(tmp_path: Path) -> None:
    """The cross-phase contract from Step 4.1: the rendered charter must
    carry every CHARTER_REQUIRED_FIELDS key the scaffold test asserts."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")

    charter = workspace_file(tmp_path, "charters/CH-001.md")
    fm = read_frontmatter(charter)
    for required in ("id", "mission", "target", "time-box", "risk-areas", "acceptance-criteria"):
        assert required in fm, f"frontmatter missing {required!r}: {sorted(fm)}"
    assert fm["id"] == "CH-001"
    assert "Sign-in flow" in fm["target"]


def test_charter_passes_well_formed_shape(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")

    charter = workspace_file(tmp_path, "charters/CH-001.md").read_text(encoding="utf-8")
    # Required body sections per the seeded fixture's structure.
    for heading in ("## Mission", "## Target Area", "## Time-Box", "## Risk Areas",
                    "## Acceptance Criteria", "## Out of Scope", "## Phase 3 Sources"):
        assert heading in charter, (
            f"charter body missing required section heading: {heading}"
        )


def test_phase_3_sources_lists_artifacts_consumed(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")

    charter = workspace_file(tmp_path, "charters/CH-001.md").read_text(encoding="utf-8")
    # The helper must list every Phase 3 artifact it actually read.
    assert "product-knowledge/entities.md" in charter
    assert "product-knowledge/user-journeys.md" in charter
    assert "requirements/open-questions.md" in charter


# ---------------------------------------------------------------------------
# Auto-suggestion path
# ---------------------------------------------------------------------------


def test_auto_suggestion_picks_highest_mention_entity(tmp_path: Path) -> None:
    """Without --target/--mission, the helper picks the entity with the
    most mentions across product-knowledge + open-questions. The seeded
    state mentions ``Workspace`` four times (entities.md ×2, user-journey
    ×1, open-questions ×3) versus ``Account`` once."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path, top_entity="Workspace")
    run_helper(tmp_path)

    charter = workspace_file(tmp_path, "charters/CH-001.md")
    text = charter.read_text(encoding="utf-8")
    fm = read_frontmatter(charter)
    assert "Workspace" in fm["target"] or "Workspace" in text


def test_auto_suggestion_ties_broken_alphabetically(tmp_path: Path) -> None:
    """When two entities have identical mention counts, the helper picks
    the alphabetically-earlier name. This guarantees deterministic output
    across machines and re-runs."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(
        tmp_path,
        top_entity="Beta",  # 4 mentions total
        other_entities=("Alpha",),  # 1 mention - won't tie
    )
    # The seed mentions ``Beta`` heavily; override open-questions to make
    # Alpha tie with Beta on total mention count.
    workspace_file(tmp_path, "requirements/open-questions.md").write_text(
        "# Open questions\n\n"
        "- [tc-knowledge/learn-from-docs] Alpha is used but undefined.\n"
        "- [tc-knowledge/learn-from-docs] Alpha is used but undefined again.\n"
        "- [tc-knowledge/learn-from-docs] Alpha needs another mention.\n",
        encoding="utf-8",
    )
    # entities.md mentions Beta twice (## From documents + ## From code) plus
    # user-journey once = 3; Alpha 1 (entities) + 3 (open-questions) = 4.
    # Adjust entities so they tie at 4:4 (Beta: 3 entity sections + 1 journey;
    # Alpha: 1 entity + 3 open-questions). Actually let's make this simpler -
    # put both into entities.md and open-questions equally.
    workspace_file(tmp_path, "product-knowledge/entities.md").write_text(
        "# Entities\n\n## From documents\n\n"
        "- **Alpha** (file:1)\n"
        "- **Beta** (file:2)\n\n",
        encoding="utf-8",
    )
    workspace_file(tmp_path, "product-knowledge/user-journeys.md").write_text(
        "# User Journeys\n\n## From documents\n\n"
        "- **Sign in** (file:1) - 3 steps\n",
        encoding="utf-8",
    )
    workspace_file(tmp_path, "requirements/open-questions.md").write_text(
        "# Open questions\n\n"
        "- [tc-knowledge/learn-from-docs] Alpha is undefined.\n"
        "- [tc-knowledge/learn-from-docs] Beta is undefined.\n",
        encoding="utf-8",
    )
    run_helper(tmp_path)
    charter = workspace_file(tmp_path, "charters/CH-001.md").read_text(encoding="utf-8")
    fm = read_frontmatter(workspace_file(tmp_path, "charters/CH-001.md"))
    # Alphabetically earlier = Alpha.
    assert "Alpha" in fm["target"] or "Alpha" in charter, (
        f"expected Alpha (alphabetically earlier) to win the tie; got target={fm.get('target')}"
    )


# ---------------------------------------------------------------------------
# Idempotency + --new-id
# ---------------------------------------------------------------------------


def test_idempotent_rerun_same_target(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")
    first = workspace_file(tmp_path, "charters/CH-001.md").read_bytes()

    proc = run_helper(tmp_path, "--target", "Sign-in flow")
    second = workspace_file(tmp_path, "charters/CH-001.md").read_bytes()
    assert first == second, "charter must be byte-identical on idempotent re-run"
    # CLI reports skip.
    stdout_lower = proc.stdout.lower()
    assert "skip" in stdout_lower or "already exists" in stdout_lower


def test_new_id_flag_reallocates(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")

    # Re-run with --new-id forces a fresh allocation even with the same target.
    run_helper(tmp_path, "--target", "Sign-in flow", "--new-id")

    ch_001 = workspace_file(tmp_path, "charters/CH-001.md")
    ch_002 = workspace_file(tmp_path, "charters/CH-002.md")
    assert ch_001.is_file(), "CH-001 must still exist"
    assert ch_002.is_file(), "CH-002 must be allocated on --new-id"


def test_user_edits_preserved_on_skip(tmp_path: Path) -> None:
    """When the helper skips an existing charter, user edits to the body
    must be preserved byte-for-byte. Mirrors the Phase 2 Step 2.6
    skip-not-overwrite idempotency contract for downstream-enriched
    artifacts."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)
    run_helper(tmp_path, "--target", "Sign-in flow")

    # Simulate a user edit.
    charter_path = workspace_file(tmp_path, "charters/CH-001.md")
    original = charter_path.read_text(encoding="utf-8")
    edited = original + "\n## User Notes\n\nManual edits live below the generated body.\n"
    charter_path.write_text(edited, encoding="utf-8")
    edited_bytes = charter_path.read_bytes()

    # Re-run idempotently.
    run_helper(tmp_path, "--target", "Sign-in flow")
    after_bytes = charter_path.read_bytes()
    assert after_bytes == edited_bytes, (
        "user edits must be preserved when the helper skips an existing charter"
    )


# ---------------------------------------------------------------------------
# Config extensions
# ---------------------------------------------------------------------------


def test_risk_keywords_extension_applied(tmp_path: Path) -> None:
    """tc-explore.charters.risk-keywords extends the universal core
    additively. Adding a domain-specific risk keyword causes
    risk-register entries matching that keyword to surface as
    risk-areas in the generated charter."""
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)

    # Populate the risk-register with a project-specific risk entry.
    workspace_file(tmp_path, "risk-register/risk-register.md").write_text(
        "# Risk Register\n\n"
        "- PCI: storing primary account numbers in plaintext.\n"
        "- Session: token leakage via console logging.\n",
        encoding="utf-8",
    )

    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-explore:\n"
        "  charters:\n"
        "    risk-keywords: [PCI]\n",
        encoding="utf-8",
    )

    run_helper(tmp_path, "--target", "Sign-in flow")
    charter = workspace_file(tmp_path, "charters/CH-001.md").read_text(encoding="utf-8")
    # The PCI risk entry should surface as a risk area in the charter.
    assert "PCI" in charter, (
        "risk-keywords extension must surface project-specific risk entries"
    )


def test_area_keywords_extension_applied(tmp_path: Path) -> None:
    run_init(tmp_path)
    seed_minimal_phase_3_state(tmp_path)

    config = workspace_file(tmp_path, "config.yaml")
    base = config.read_text(encoding="utf-8") if config.is_file() else ""
    config.write_text(
        base.rstrip()
        + "\n\ntc-explore:\n"
        "  charters:\n"
        "    area-keywords: [checkout]\n",
        encoding="utf-8",
    )

    # Provide a mission containing the extended area keyword.
    run_helper(tmp_path, "--mission", "Discover whether the checkout completes correctly.")
    charter = workspace_file(tmp_path, "charters/CH-001.md").read_text(encoding="utf-8")
    # The 'checkout' keyword should be recognized; behavior in v1 is to
    # accept the user's mission verbatim. The presence of the keyword in
    # the charter target is what the test asserts.
    assert "checkout" in charter.lower()
