"""Step 5.3 - /tc:review-bdd (review_bdd) end-to-end tests.

Drives ``review_bdd.py`` against a tmp workspace seeded with the deliberately
flawed ``flawed.feature`` (one defect per universal review category) and with a
clean feature generated by ``/tc:generate-bdd``. Also asserts that
``/tc:generate-bdd`` auto-runs the shared ``review_features()`` after
generation (suppressible with ``--no-review``).

Asserts the Step 5.3 contract from planning/plan.md:

- uninitialized workspace refused (exit 2);
- no ``.feature`` files refused with a precondition error pointing at
  ``/tc:generate-bdd`` (exit 2);
- the seeded ``flawed.feature`` surfaces every one of the six universal review
  categories exactly once as ``[bdd-review]`` gap signals;
- gap signals carry the per-area ``source-id`` and dedup across re-runs;
- a clean (generated) feature produces a ``pass`` verdict and zero signals;
- ``review_features()`` is the same code path ``/tc:generate-bdd`` auto-runs;
  ``--no-review`` suppresses the auto-run.
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "plugins" / "test-commander" / "scripts"
REVIEW = SCRIPTS / "review_bdd.py"
GENERATE = SCRIPTS / "generate_bdd.py"
INIT = SCRIPTS / "init_workspace.py"

FIXTURE_DIR = REPO / "tests" / "fixtures" / "seeded-bdd"
FIXTURE_FEATURE = FIXTURE_DIR / "flawed.feature"
FIXTURE_TEST_IDEA = FIXTURE_DIR / "REQ-001.md"
FIXTURE_SESSION = FIXTURE_DIR / "SESS-20260115-001.md"

REVIEW_CATEGORIES = [
    "ambiguous-step",
    "missing-tag",
    "untraceable",
    "ui-coupled-step",
    "missing-examples",
    "conjunction-overload",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def run_init(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True, text=True, check=True,
    )


def run_review(project_root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(REVIEW), str(project_root), *args],
        capture_output=True, text=True,
    )


def run_generate(project_root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GENERATE), str(project_root), *args],
        capture_output=True, text=True,
    )


def seed_flawed(project_root: Path) -> Path:
    run_init(project_root)
    ws = project_root / ".test-commander"
    (ws / "bdd" / "features").mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURE_FEATURE, ws / "bdd" / "features" / "flawed.feature")
    return ws


def seed_clean(project_root: Path) -> Path:
    run_init(project_root)
    ws = project_root / ".test-commander"
    (ws / "test-ideas").mkdir(parents=True, exist_ok=True)
    (ws / "sessions").mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURE_TEST_IDEA, ws / "test-ideas" / "REQ-001.md")
    shutil.copy(FIXTURE_SESSION, ws / "sessions" / "SESS-20260115-001.md")
    return ws


def open_questions_lines(ws: Path) -> list[str]:
    target = ws / "requirements" / "open-questions.md"
    if not target.is_file():
        return []
    return [
        ln for ln in target.read_text(encoding="utf-8").splitlines()
        if "[bdd-review]" in ln
    ]


def load(name: str, path: Path):
    if str(SCRIPTS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS))  # generate_bdd imports sibling review_bdd
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_uninitialized_workspace_refused(tmp_path):
    result = run_review(tmp_path)
    assert result.returncode == 2, result.stderr
    assert "init" in result.stderr.lower()


def test_no_features_refused(tmp_path):
    run_init(tmp_path)
    result = run_review(tmp_path)
    assert result.returncode == 2, result.stdout
    assert "/tc:generate-bdd" in result.stderr


# ---------------------------------------------------------------------------
# Rubric coverage
# ---------------------------------------------------------------------------


def test_flawed_feature_surfaces_every_category_once(tmp_path):
    ws = seed_flawed(tmp_path)
    result = run_review(tmp_path)
    assert result.returncode == 0, result.stderr
    lines = open_questions_lines(ws)
    for cat in REVIEW_CATEGORIES:
        hits = [ln for ln in lines if cat in ln]
        assert len(hits) == 1, f"category {cat} surfaced {len(hits)} times: {hits}"
    assert len(lines) == len(REVIEW_CATEGORIES), f"unexpected signals: {lines}"


def test_gap_signals_carry_source_id(tmp_path):
    ws = seed_flawed(tmp_path)
    run_review(tmp_path)
    lines = open_questions_lines(ws)
    assert lines, "expected gap signals"
    for ln in lines:
        assert "[tc-bdd/bdd-review-flawed]" in ln, ln


def test_idempotent_rerun_no_duplicate_signals(tmp_path):
    ws = seed_flawed(tmp_path)
    run_review(tmp_path)
    first = open_questions_lines(ws)
    run_review(tmp_path)
    second = open_questions_lines(ws)
    assert first == second, "re-run must not duplicate [bdd-review] signals"


# ---------------------------------------------------------------------------
# Clean feature passes
# ---------------------------------------------------------------------------


def test_clean_generated_feature_passes(tmp_path):
    ws = seed_clean(tmp_path)
    run_generate(tmp_path, "--no-review")
    result = run_review(tmp_path)
    assert result.returncode == 0, result.stderr
    assert open_questions_lines(ws) == [], "clean feature must produce no signals"
    summary = next((ws / "bdd" / "summaries").glob("account-*.md"))
    body = summary.read_text(encoding="utf-8")
    assert "Review verdict: pass" in body, body


# ---------------------------------------------------------------------------
# Shared code path + generate-bdd auto-run wiring
# ---------------------------------------------------------------------------


def test_review_features_is_shared_codepath():
    review_mod = load("review_bdd", REVIEW)
    generate_mod = load("generate_bdd", GENERATE)
    assert hasattr(review_mod, "review_features"), "review_bdd must expose review_features"
    assert generate_mod.review_features is review_mod.review_features, (
        "generate_bdd must import and reuse review_bdd.review_features"
    )


def test_generate_auto_runs_review_updates_verdict(tmp_path):
    ws = seed_clean(tmp_path)
    run_generate(tmp_path)  # default: auto-review on
    summary = next((ws / "bdd" / "summaries").glob("account-*.md"))
    assert "Review verdict: pass" in summary.read_text(encoding="utf-8")


def test_generate_no_review_leaves_pending(tmp_path):
    ws = seed_clean(tmp_path)
    run_generate(tmp_path, "--no-review")
    summary = next((ws / "bdd" / "summaries").glob("account-*.md"))
    assert "Review verdict: (pending /tc:review-bdd)" in summary.read_text(encoding="utf-8")
