"""Step 5.4 - /tc:traceability-map (traceability_map) end-to-end tests.

Drives ``traceability_map.py`` against a tmp workspace seeded with a generated
requirements inventory plus (optionally) the seeded enriched ``REQ-001.md`` and
a feature generated by ``/tc:generate-bdd``. The helper is the authoritative
regenerator of ``traceability/requirements-map.md`` (the shared 4-column format
Phase 2 also writes) and the new ``traceability/test-map.md`` (scenario-level
chain with ``pending`` downstream links).

Asserts the Step 5.4 contract from planning/plan.md:

- uninitialized workspace refused (exit 2);
- no ``.feature`` files -> requirements-map.md written with every requirement
  present (BDD-features cell ``_(none)_``), test-map.md written with the
  empty-note (not an error);
- the seeded chain -> test-map.md links REQ-001 to its CS IDs and the generated
  scenarios with ``pending`` downstream columns; requirements-map.md lists the
  feature file for REQ-001;
- idempotent re-run is byte-identical;
- the shared ``traceability_render.render_requirements_map`` is byte-identical
  for the Phase-2 and Phase-5 callers given the same links (extraction left
  requirements_coverage output unchanged).
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import requirements_coverage
import traceability_render

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "plugins" / "test-commander" / "scripts"
HELPER = SCRIPTS / "traceability_map.py"
INIT = SCRIPTS / "init_workspace.py"
GENERATE = SCRIPTS / "generate_bdd.py"

FIXTURE_DIR = REPO / "tests" / "fixtures" / "seeded-bdd"
FIXTURE_TEST_IDEA = FIXTURE_DIR / "REQ-001.md"
FIXTURE_SESSION = FIXTURE_DIR / "SESS-20260115-001.md"

INVENTORY = """# Requirements Inventory

Total: **3** requirements parsed.

| REQ-ID | Title |
| --- | --- |
| REQ-001 | Account sign-in with email and password |
| REQ-002 | Workspace asset upload |
| REQ-003 | Session expiry handling |
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def run_init(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(INIT), str(project_root)],
        capture_output=True, text=True, check=True,
    )


def run_map(project_root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(HELPER), str(project_root), *args],
        capture_output=True, text=True,
    )


def run_generate(project_root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GENERATE), str(project_root), *args],
        capture_output=True, text=True,
    )


def seed_inventory(project_root: Path) -> Path:
    run_init(project_root)
    ws = project_root / ".test-commander"
    (ws / "requirements").mkdir(parents=True, exist_ok=True)
    (ws / "requirements" / "requirements-inventory.md").write_text(INVENTORY, encoding="utf-8")
    return ws


def seed_chain(project_root: Path) -> Path:
    """Inventory + enriched REQ-001 + a generated feature."""
    ws = seed_inventory(project_root)
    (ws / "test-ideas").mkdir(parents=True, exist_ok=True)
    (ws / "sessions").mkdir(parents=True, exist_ok=True)
    shutil.copy(FIXTURE_TEST_IDEA, ws / "test-ideas" / "REQ-001.md")
    shutil.copy(FIXTURE_SESSION, ws / "sessions" / "SESS-20260115-001.md")
    run_generate(project_root, "--no-review")
    return ws


def read(ws: Path, name: str) -> str:
    return (ws / "traceability" / name).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------


def test_uninitialized_workspace_refused(tmp_path):
    result = run_map(tmp_path)
    assert result.returncode == 2, result.stderr
    assert "init" in result.stderr.lower()


# ---------------------------------------------------------------------------
# No features: maps still written
# ---------------------------------------------------------------------------


def test_no_features_writes_maps_without_error(tmp_path):
    ws = seed_inventory(tmp_path)
    result = run_map(tmp_path)
    assert result.returncode == 0, result.stderr
    req_map = read(ws, "requirements-map.md")
    for rid in ("REQ-001", "REQ-002", "REQ-003"):
        assert rid in req_map, f"{rid} missing from requirements map"
    assert "_(none)_" in req_map, "BDD-features cell should read _(none)_ with no features"
    test_map = read(ws, "test-map.md")
    assert "No BDD scenarios" in test_map


# ---------------------------------------------------------------------------
# Seeded chain
# ---------------------------------------------------------------------------


def test_test_map_links_requirement_through_scenarios(tmp_path):
    ws = seed_chain(tmp_path)
    result = run_map(tmp_path)
    assert result.returncode == 0, result.stderr
    test_map = read(ws, "test-map.md")
    assert "REQ-001" in test_map
    for cs in ("CS-001-001", "CS-001-002", "CS-001-003"):
        assert cs in test_map, f"{cs} missing from test-map"
    # downstream columns are pending, never invented
    assert "pending" in test_map
    assert "Expired session routes the holder back to sign-in" in test_map


def test_requirements_map_lists_feature_for_req(tmp_path):
    ws = seed_chain(tmp_path)
    run_map(tmp_path)
    req_map = read(ws, "requirements-map.md")
    assert "REQ-001" in req_map
    assert "bdd/features/" in req_map, "requirements-map should list the feature file"


def test_idempotent_rerun_byte_identical(tmp_path):
    ws = seed_chain(tmp_path)
    run_map(tmp_path)
    first_req = (ws / "traceability" / "requirements-map.md").read_bytes()
    first_test = (ws / "traceability" / "test-map.md").read_bytes()
    run_map(tmp_path)
    assert (ws / "traceability" / "requirements-map.md").read_bytes() == first_req
    assert (ws / "traceability" / "test-map.md").read_bytes() == first_test


# ---------------------------------------------------------------------------
# Shared renderer regression
# ---------------------------------------------------------------------------


def test_shared_renderer_identical_for_both_callers():
    req_ids = ["REQ-001", "REQ-002"]
    rows = [
        ("REQ-001", ["test-ideas/REQ-001.md"], ["bdd/features/x.feature"], []),
        ("REQ-002", [], [], []),
    ]
    out_a = traceability_render.render_requirements_map(req_ids, rows)
    out_b = traceability_render.render_requirements_map(req_ids, rows)
    assert out_a == out_b
    # requirements_coverage delegates to the same shared renderer
    links = [
        requirements_coverage.CoverageLink(
            req_id="REQ-001",
            test_ideas=["test-ideas/REQ-001.md"],
            bdd_features=["bdd/features/x.feature"],
            automation=[],
        ),
        requirements_coverage.CoverageLink(req_id="REQ-002"),
    ]
    via_coverage = requirements_coverage._render_traceability_map(req_ids, links)
    assert via_coverage == out_a, "requirements_coverage must delegate to the shared renderer"
