# Generated by /tc:generate-bdd from test-ideas/<REQ-ID>.md
# Source candidates: <SESS-ID, ...>
# Deterministic scaffold - refine Given/When/Then phrasing and promote to
# Scenario Outline where data-driven, per methodology/bdd-generation.md.

@area:<area>
Feature: <requirement title>

  @area:<area> @req:<REQ-ID> @cs:<CS-ID> <class tag> [@exploratory @anomaly:<category>]
  Scenario: <candidate title>
    Given an account in the "<requirement title>" context
    When the <type> behavior "<candidate title>" is exercised
    Then the outcome described by "<candidate title>" holds

# Notes for the refinement (Claude judgment layer):
# - Replace the scaffold steps with concrete, behavior-level Given/When/Then.
# - Promote to `Scenario Outline` with an `Examples:` table when data-driven.
# - Keep one behavior per step (no `and`-chained steps).
# - Add project namespace values (@risk:, @persona:) where they apply.
