"""MockAgentAdapter - deterministic, no real execution (Phase 10.5 Step 10.5.2).

Used to build and test the whole governed pipeline hermetically. It "executes" a
bounded instruction by creating exactly the instruction's `expected_outputs`
(so a post-execution diff matches the plan), records every call, and reports
files changed / artifacts created. It refuses an unplanned call.
"""

from __future__ import annotations

from collections.abc import Iterator

from agent_adapters.base import (
    AgentAdapter,
    BoundedInstruction,
    ExecutionResult,
    require_planned,
)


class MockAgentAdapter(AgentAdapter):
    def __init__(self) -> None:
        self.calls: list[BoundedInstruction] = []
        self._last: ExecutionResult | None = None

    def execute_command(self, instruction: BoundedInstruction | None) -> ExecutionResult:
        instr = require_planned(instruction)
        self.calls.append(instr)
        changed: list[str] = []
        for rel in instr.expected_outputs:
            dest = instr.project_root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(
                f"// generated by MockAgentAdapter for {instr.command}\n", encoding="utf-8"
            )
            changed.append(rel)
        self._last = ExecutionResult(
            status="succeeded",
            files_changed=sorted(changed),
            artifacts_created=sorted(changed),
            usage=None,
            summary=f"mock executed {instr.command}",
            events=list(self.stream_events(instr)),
        )
        return self._last

    def stream_events(self, instruction: BoundedInstruction | None) -> Iterator[str]:
        instr = require_planned(instruction)
        yield f"start: {instr.command}"
        for rel in instr.expected_outputs:
            yield f"write: {rel}"
        yield f"done: {instr.command}"

    def capture_result(self) -> ExecutionResult | None:
        return self._last

    def report_files_changed(self) -> list[str]:
        return list(self._last.files_changed) if self._last else []

    def report_artifacts_created(self) -> list[str]:
        return list(self._last.artifacts_created) if self._last else []

    def report_usage_if_available(self) -> dict | None:
        return self._last.usage if self._last else None
